/**
 * Plain-English explanations shown when someone hovers (or presses and holds)
 * a button, so they know what it does before they press it.
 *
 * Keys are matched against the button's visible text (lowercased, trimmed).
 * Add new entries here — every button with that label across the app picks it up.
 */
export const BUTTON_HINTS: Record<string, string> = {
  // Saving / submitting
  save: "Saves your changes.",
  "save changes": "Saves your changes.",
  submit: "Sends this form in.",
  create: "Creates a new item with what you've filled in.",
  add: "Adds a new item to the list.",
  update: "Saves the new information over the old.",
  confirm: "Confirms this and continues.",
  continue: "Moves on to the next step.",
  next: "Goes to the next step.",
  back: "Goes back one step.",
  finish: "Completes this and closes it out.",
  apply: "Applies what you've chosen.",
  send: "Sends this out now.",
  "send email": "Sends the email now.",
  "send test": "Sends a test version to you first.",
  publish: "Makes this visible to everyone.",
  approve: "Marks this as accepted.",
  reject: "Marks this as turned down.",
  verify: "Checks this and marks it as confirmed.",

  // Leaving / undoing
  cancel: "Closes this without saving anything.",
  close: "Closes this window.",
  dismiss: "Hides this message.",
  reset: "Puts everything back to how it started.",
  clear: "Empties what you've entered.",
  "clear filters": "Removes all filters and shows everything again.",
  delete: "Permanently removes this. This can't be undone.",
  remove: "Takes this off the list.",
  archive: "Moves this out of the way without deleting it.",
  deactivate: "Turns this off so it stops showing.",
  activate: "Turns this on so it starts showing.",

  // Getting things out
  export: "Downloads this list as a spreadsheet.",
  "export csv": "Downloads this list as a spreadsheet you can open in Excel.",
  "export pdf": "Downloads this as a PDF document.",
  download: "Saves a copy to your computer.",
  print: "Opens the print window.",
  copy: "Copies this to your clipboard so you can paste it elsewhere.",
  "copy link": "Copies the web address so you can paste it anywhere.",
  "copy email": "Copies the email text so you can paste it into your mail app.",
  share: "Gives you a way to send this to someone else.",

  // Getting things in
  import: "Brings in information from a file.",
  upload: "Adds a file from your computer.",
  "choose file": "Picks a file from your computer.",
  browse: "Opens your files to pick one.",

  // Looking around
  refresh: "Reloads the latest information.",
  reload: "Reloads the latest information.",
  search: "Finds matches for what you typed.",
  filter: "Narrows the list down to what you choose.",
  "view all": "Shows the full list.",
  "view details": "Opens the full information for this item.",
  details: "Opens the full information for this item.",
  edit: "Opens this so you can change it.",
  preview: "Shows how this will look before it goes out.",
  "learn more": "Opens more information about this.",
  retry: "Tries that again.",
  "try again": "Tries that again.",

  // Accounts
  "sign in": "Logs you into your account.",
  "log in": "Logs you into your account.",
  "sign up": "Creates a new account for you.",
  "sign out": "Logs you out of your account.",
  "log out": "Logs you out of your account.",
  register: "Creates a new account for you.",

  // Money
  subscribe: "Starts a paid plan.",
  upgrade: "Moves you to a bigger plan with more included.",
  checkout: "Takes you to payment.",
  "buy now": "Takes you straight to payment.",
  pay: "Takes you to payment.",
  "manage subscription": "Opens your plan so you can change or cancel it.",

  // Admin — adding things
  "add lead": "Adds a new business lead by hand.",
  "add target": "Adds a company to your outreach list.",
  "add prospect": "Adds a new company you want to sponsor you.",
  "add reminder": "Sets a reminder so you don't forget to follow up.",
  "create reminder": "Sets a reminder so you don't forget to follow up.",
  "add material": "Uploads a new marketing file to the library.",
  "bulk upload": "Uploads several files at once.",
  "add beta tester": "Invites someone to try the app early.",
  "invite stays tester": "Invites someone to try Mansa Stays early.",
  "add seat": "Gives one more person access under this partner.",
  "manual entry": "Type a business in yourself instead of importing.",
  "use smart paste": "Paste messy text and it fills the fields for you.",
  "new announcement": "Writes a new message to send out to everyone.",
  "new suspension": "Blocks an account from using the app.",
  "new token": "Creates a new access key for developers.",
  "new webhook": "Sets up an automatic alert to another system.",
  "new backup": "Makes a fresh copy of your data right now.",
  "create backup": "Makes a fresh copy of your data right now.",
  "new campaign": "Starts a new outreach campaign.",
  "create campaign": "Starts a new outreach campaign.",
  "new import": "Starts bringing in a new batch of businesses.",
  "new scheduled search": "Sets up a search that runs on its own on a schedule.",
  "create api key": "Creates a new key so another service can connect.",
  "create code": "Creates a new discount code.",
  "create promo code": "Creates a new discount code.",
  "create flag": "Creates a switch that turns a feature on or off.",
  "create feature flag": "Creates a switch that turns a feature on or off.",
  "create role": "Creates a new permission level for staff.",
  provision: "Sets this developer up with access.",
  seed: "Fills the database with sample information for testing.",

  // Admin — reviewing and deciding
  "approve & publish": "Accepts this and puts it live on the site.",
  "mark approved": "Marks this as accepted.",
  "mark reviewed": "Marks this as looked at and handled.",
  "mark resolved": "Marks this issue as taken care of.",
  "mark under review": "Flags this as being looked into right now.",
  "mark completed": "Marks this as finished.",
  "mark contacted": "Notes that you've reached out to this company.",
  "mark all read": "Clears the unread mark on all notifications.",
  "mark paid": "Records that this money has been sent.",
  "mark as paid": "Records that this money has been sent.",
  "confirm paid": "Confirms the payment went out.",
  "needs more info": "Sends this back asking for more details.",
  "reject listing": "Turns down this business listing.",
  reinstate: "Puts this back on the site after it was removed.",
  reactivate: "Turns this back on.",
  deny: "Turns down this request.",
  warn: "Sends a warning without removing anything.",
  flag: "Marks this as suspicious for a closer look.",
  reverse: "Undoes this action and puts things back.",
  resolve: "Closes this out as handled.",
  review: "Opens this so you can look it over.",
  prioritize: "Moves this to the top of the list.",
  "correct — publish": "Confirms the details are right and puts it live.",
  "wrong — reject": "Marks the details as wrong and turns it down.",
  "it is black-owned": "Confirms this business is Black-owned.",
  "keep it": "Leaves this listing on the site.",
  "remove from directory": "Takes this business off the public directory.",
  "remove all unreachable listings": "Removes every listing whose website no longer works.",
  "reject all with no ownership evidence": "Turns down every listing with no proof of ownership.",
  "re-verify": "Runs the checks on this listing again.",
  "re-run kayla": "Has Kayla take another look at this.",

  // Admin — accounts and access
  suspend: "Blocks this account from using the app.",
  "suspend account": "Blocks this account from using the app.",
  "suspend selected": "Blocks every account you've ticked.",
  "lift": "Removes the block on this account.",
  "lift suspension": "Removes the block so they can use the app again.",
  revoke: "Cancels this access immediately.",
  "verify selected": "Marks everything you've ticked as confirmed.",
  "unverify selected": "Removes the confirmed mark from everything you've ticked.",
  "delete selected": "Permanently removes everything you've ticked. This can't be undone.",
  "send notification": "Sends a message to the people you've picked.",
  "select all": "Ticks every item on the list.",
  "deselect all": "Unticks everything.",
  "start viewing as this user": "Lets you see the app exactly as this person sees it.",
  "end session": "Stops viewing as that person and returns to your own account.",
  "toggle theme": "Switches between light and dark colors.",

  // Admin — importing and data
  "import csv": "Brings in businesses from a spreadsheet file.",
  "import from url": "Pulls business details in from a web address.",
  "import business": "Adds this business to your directory.",
  "import chapters": "Brings in a list of chapters from a file.",
  "download template": "Gets you the blank spreadsheet to fill in.",
  "start import": "Begins bringing the file's information in.",
  "validate leads": "Checks the list for errors before importing.",
  "ai discovery": "Lets Kayla go find new businesses for you.",
  "fetch images": "Goes and finds photos for this listing.",
  "pull real photos": "Replaces placeholder pictures with real ones.",
  "partner directories only": "Only pulls photos from trusted partner sites.",
  stop: "Stops what's running right now.",
  "start over": "Clears this and begins again.",
  "done editing": "Finishes editing and locks the changes in.",
  done: "Closes this out.",
  "enrich 50 now": "Fills in missing details for the next 50 records.",
  "check next 25": "Runs the check on the next 25 records.",
  "check next 50": "Runs the check on the next 50 records.",
  "draw random leads": "Pulls a random sample to spot-check.",

  // Admin — outreach and sponsors
  "copy subject": "Copies the email subject line.",
  "copy letter": "Copies the whole letter so you can paste it into email.",
  "copy to clipboard": "Copies this so you can paste it elsewhere.",
  "open in email app": "Opens this message in your email program.",
  "follow up in 5 days": "Sets a reminder to check back in 5 days.",
  "follow up in 10 days": "Sets a reminder to check back in 10 days.",
  "save next action": "Saves what you plan to do next with this company.",
  "save notes": "Saves what you've written down.",
  "meeting agenda": "Opens a ready-made agenda for your meeting.",
  "sponsor wall preview": "Shows how their logo would look on the sponsor wall.",
  "open live sponsor wall": "Opens the real sponsor wall page.",
  "partnership portal": "Opens the sponsor's own portal page.",
  "partner portal": "Opens the partner's portal page.",
  "developer portal": "Opens the area built for developers.",
  website: "Opens this company's website in a new tab.",
  "send invite": "Emails an invitation to this business.",
  "send batch": "Sends this group of messages out now.",
  "preview count": "Shows how many would be sent, without sending.",
  "preview pending batches": "Shows what's waiting to go out, without sending.",
  "check payment": "Checks whether their payment has come through.",
  invoice: "Opens the bill for this agreement.",
  certificate: "Opens their sponsorship certificate.",
  complete: "Marks this step as done.",
  "clear filter": "Removes the filter and shows everything again.",

  // Admin — money
  refund: "Sends the money back to the customer.",
  "refund via stripe": "Sends the money back through the card processor.",
  "record payout": "Notes down a payment you've sent out.",
  "cancel booking": "Cancels this reservation.",
  "cancel at period end": "Keeps the plan running until the paid period ends, then stops it.",
  "cancel immediately": "Stops the plan right now.",
  "apply credit to customer balance": "Puts credit on their account for future bills.",
  "save pricing": "Saves the new prices.",

  // Admin — reports, exports, system
  "export to csv": "Downloads this list as a spreadsheet.",
  csv: "Downloads as a spreadsheet file.",
  json: "Downloads as a data file for developers.",
  "download mp4": "Saves the video to your computer.",
  "print / save as pdf": "Opens the print window, where you can also save as a PDF.",
  "schedule report": "Sets this report to be sent automatically.",
  "run now": "Runs this right now instead of waiting.",
  "trigger sweep": "Runs the clean-up pass right now.",
  "run cleanup": "Clears out old, unneeded records.",
  "run archive": "Moves old records into storage.",
  "save all": "Saves every change on this page.",
  "save settings": "Saves these settings.",
  "quick maintenance": "Puts the site into maintenance mode for a short while.",
  "refresh data": "Reloads the latest information.",
  "set cap": "Sets a spending limit for this assistant.",
  "update alert": "Saves changes to this alert.",
  "generate announcement": "Has Kayla write the announcement for you.",
  regenerate: "Has Kayla write another version.",
  generate: "Creates this for you automatically.",
  "ask kayla": "Ask your AI assistant a question about this.",
  "analyze all": "Has Kayla look over everything here.",
  "analyze recent": "Has Kayla look over the most recent activity.",
  "analyze top businesses": "Has Kayla look at your best-performing businesses.",
  "analyze top users": "Has Kayla look at your most active members.",

  // Admin — navigation and viewing
  "back to admin": "Returns to the admin area.",
  "back to dashboard": "Returns to your dashboard.",
  "back to sponsors": "Returns to the sponsor list.",
  "back to patents": "Returns to the patent documents.",
  hub: "Opens the main admin hub.",
  tour: "Walks you through this page step by step.",
  analytics: "Shows the numbers and trends for this.",
  view: "Opens this to look at it.",
  open: "Opens this.",
  "view listing": "Opens the business's page.",
  "view public page": "Shows the page the way visitors see it.",
  "view protected claims": "Opens the confidential patent claims.",
  "view & download team nda": "Opens the confidentiality agreement and lets you save it.",
  "view stripe dashboard": "Opens your payment account in a new tab.",
  "view supabase dashboard": "Opens the database admin site in a new tab.",
  "sign up for resend": "Opens the email service site to create an account.",
  "verify domain": "Confirms you own this web address so email can send from it.",
  "test authentication flow": "Runs a test of the sign-in process.",
  "test stripe integration": "Runs a test payment to check the setup works.",
};

/** Pulls readable text out of a button's children so we can look up a hint. */
export function extractButtonText(node: React.ReactNode): string {
  if (node === null || node === undefined || typeof node === "boolean") return "";
  if (typeof node === "string" || typeof node === "number") return String(node);
  if (Array.isArray(node)) return node.map(extractButtonText).join(" ");
  const el = node as { props?: { children?: React.ReactNode } };
  if (el && el.props && el.props.children !== undefined) {
    return extractButtonText(el.props.children);
  }
  return "";
}

export function getButtonHint(text: string): string | undefined {
  const key = text.replace(/\s+/g, " ").trim().toLowerCase().replace(/[.…]+$/, "");
  if (!key) return undefined;
  return BUTTON_HINTS[key];
}
