import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { ChevronDown, Building2, Handshake, Network } from 'lucide-react';

/**
 * Multi-Site / National Organizations — collapsible revenue-sharing entry point.
 * Sits directly under the business registration box on the homepage.
 */
const MultiSiteRevenueShareCard: React.FC = () => {
  const [open, setOpen] = useState(false);

  return (
    <section className="relative w-full px-4 pb-8" aria-labelledby="multisite-heading">
      <div
        className="max-w-3xl mx-auto bg-white rounded-md shadow-2xl overflow-hidden"
        style={{ border: '1px solid #e5e7eb' }}
      >
        {/* Header band */}
        <div style={{ background: '#003366' }} className="px-6 md:px-8 py-5 relative">
          <div className="absolute top-0 left-0 right-0 h-1" style={{ background: '#FFB300' }} />
          <div className="flex items-center gap-3 mb-2">
            <div className="h-px w-8" style={{ background: '#FFB300' }} />
            <span
              className="text-[11px] font-semibold tracking-[0.2em] uppercase"
              style={{ color: '#FFB300' }}
            >
              Multi-Site / National Organizations
            </span>
          </div>
          <h2
            id="multisite-heading"
            className="text-2xl md:text-3xl font-semibold text-white tracking-tight leading-tight"
            style={{ fontFamily: 'Georgia, "Times New Roman", serif' }}
          >
            Revenue sharing for networks at scale.
          </h2>
          <p className="mt-1.5 text-white/75 max-w-2xl leading-relaxed text-sm">
            Franchises, church and denominational networks, chambers, associations,
            and multi-location brands.
          </p>
        </div>

        {/* Toggle */}
        <div className="px-6 md:px-8 py-5 bg-white">
          <button
            type="button"
            onClick={() => setOpen((v) => !v)}
            aria-expanded={open}
            aria-controls="multisite-details"
            className="w-full flex items-center justify-center gap-2 h-11 rounded-sm font-semibold text-sm tracking-wide uppercase border transition-colors hover:bg-neutral-50"
            style={{ borderColor: '#003366', color: '#003366' }}
          >
            {open ? 'Hide Details' : 'Revenue Sharing Opportunities'}
            <ChevronDown
              className={`w-4 h-4 transition-transform duration-300 ${open ? 'rotate-180' : ''}`}
            />
          </button>
          {!open && (
            <p className="mt-2 text-center text-xs text-neutral-500">
              For organizations with multiple locations or member businesses
            </p>
          )}
        </div>

        {/* Details */}
        <div
          id="multisite-details"
          hidden={!open}
          className="px-6 md:px-8 pb-6 border-t border-neutral-200"
        >
          <div className="grid gap-4 sm:grid-cols-3 pt-5">
            {[
              {
                icon: Network,
                title: 'Bulk Onboarding',
                desc: 'Every location or member business listed and verified in one coordinated pass.',
              },
              {
                icon: Handshake,
                title: 'Shared Revenue',
                desc: 'Your organization earns a share of subscription and transaction revenue generated by your network.',
              },
              {
                icon: Building2,
                title: 'Dedicated Kayla Deployment',
                desc: 'A branded agentic workforce configured for your members, with its own reporting.',
              },
            ].map((item) => (
              <div key={item.title}>
                <item.icon className="w-5 h-5 mb-2" style={{ color: '#003366' }} />
                <h3 className="text-sm font-semibold text-neutral-900 mb-1">{item.title}</h3>
                <p className="text-xs text-neutral-600 leading-relaxed">{item.desc}</p>
              </div>
            ))}
          </div>

          <Link
            to="/partnership-framework"
            className="mt-6 w-full inline-flex items-center justify-center h-11 rounded-sm text-white font-semibold text-sm tracking-wide uppercase transition-opacity hover:opacity-90"
            style={{ background: '#003366' }}
          >
            Request Information
          </Link>
          <p className="text-neutral-500 text-xs text-center mt-2 leading-relaxed">
            Terms are set per organization based on network size and category mix.
          </p>
        </div>
      </div>
    </section>
  );
};

export default MultiSiteRevenueShareCard;
