// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/search-directory.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { z } from "npm:zod@^3.23.8";
var EARTH_MI = 3958.8;
function haversineMiles(lat1, lng1, lat2, lng2) {
  const toRad = (d) => d * Math.PI / 180;
  const dLat = toRad(lat2 - lat1);
  const dLng = toRad(lng2 - lng1);
  const a = Math.sin(dLat / 2) ** 2 + Math.cos(toRad(lat1)) * Math.cos(toRad(lat2)) * Math.sin(dLng / 2) ** 2;
  return 2 * EARTH_MI * Math.asin(Math.sqrt(a));
}
var ANNOTATIONS = {
  title: "Search 1325.AI directory",
  readOnlyHint: true,
  idempotentHint: true,
  openWorldHint: false
};
var search_directory_default = defineTool({
  name: "search_directory",
  title: "Search 1325.AI directory",
  description: "Search the 1325.AI directory of verified Black-owned businesses in the United States. Filters by keyword, category, city, state, minimum star rating, and whether the business has a website. Supports radius search: pass latitude, longitude, and radius_miles to return businesses within that distance, sorted by distance. Results can also be sorted by rating or review count. Each result includes name, category, phone, full address, latitude/longitude, distance in miles, Google Maps and directions links, description, logo, banner image, website, verified status, average rating, review count, and a link to the business profile page on 1325.ai.",
  inputSchema: {
    query: z.string().trim().max(200).optional().describe("Keyword to match in business name or description."),
    category: z.string().trim().max(100).optional().describe("Business category, e.g. 'restaurant', 'salon', 'retail'. Use list_categories if unsure."),
    city: z.string().trim().max(100).optional().describe("City name to filter by."),
    state: z.string().trim().max(50).optional().describe("State name or 2-letter code, e.g. 'GA' or 'Georgia'."),
    latitude: z.number().min(-90).max(90).optional().describe("User's latitude for a near-me search. Must be paired with longitude."),
    longitude: z.number().min(-180).max(180).optional().describe("User's longitude for a near-me search. Must be paired with latitude."),
    radius_miles: z.number().min(1).max(250).optional().describe("Search radius in miles around latitude/longitude. Defaults to 25."),
    min_rating: z.number().min(0).max(5).optional().describe("Only return businesses with at least this average star rating (0-5)."),
    has_website: z.boolean().optional().describe("If true, only return businesses that have a website on file."),
    sort: z.enum(["best_match", "rating", "reviews", "distance"]).optional().describe(
      "Result ordering. 'distance' requires latitude/longitude. Defaults to 'distance' for near-me searches, otherwise 'best_match'."
    ),
    limit: z.number().int().min(1).max(20).optional().describe("Max results to return (1-20). Defaults to 10.")
  },
  annotations: ANNOTATIONS,
  handler: async ({
    query,
    category,
    city,
    state,
    latitude,
    longitude,
    radius_miles,
    min_rating,
    has_website,
    sort,
    limit
  }) => {
    const supabase = createClient(
      Deno.env.get("SUPABASE_URL"),
      Deno.env.get("SUPABASE_PUBLISHABLE_KEY") ?? Deno.env.get("SUPABASE_ANON_KEY"),
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const geo = typeof latitude === "number" && typeof longitude === "number" ? { lat: latitude, lng: longitude, radius: radius_miles ?? 25 } : null;
    if (!geo && (latitude != null || longitude != null)) {
      return {
        content: [
          {
            type: "text",
            text: "Near-me search needs BOTH latitude and longitude. Ask the user for their city or coordinates, then retry."
          }
        ],
        isError: true
      };
    }
    const effectiveSort = sort ?? (geo ? "distance" : "best_match");
    if (effectiveSort === "distance" && !geo) {
      return {
        content: [
          {
            type: "text",
            text: "sort='distance' requires latitude and longitude. Retry with coordinates or a different sort."
          }
        ],
        isError: true
      };
    }
    const want = limit ?? 10;
    const applyFilters = (base) => {
      let b = base;
      if (query) {
        b = b.or(`business_name.ilike.%${query}%,description.ilike.%${query}%`);
      }
      if (category) b = b.ilike("category", `%${category}%`);
      if (city) b = b.ilike("city", `%${city}%`);
      if (state) b = b.ilike("state", `%${state}%`);
      if (min_rating != null) b = b.gte("average_rating", min_rating);
      if (has_website) b = b.not("website", "is", null);
      if (geo) {
        const latDelta = geo.radius / 69;
        const lngDelta = geo.radius / (69 * Math.max(Math.cos(geo.lat * Math.PI / 180), 0.01));
        b = b.gte("latitude", geo.lat - latDelta).lte("latitude", geo.lat + latDelta).gte("longitude", geo.lng - lngDelta).lte("longitude", geo.lng + lngDelta);
      }
      return b;
    };
    let dataQuery = applyFilters(
      supabase.from("businesses").select(
        "id, slug, business_name, category, address, city, state, zip_code, latitude, longitude, description, logo_url, banner_url, website, phone, is_verified, average_rating, review_count"
      )
    );
    if (effectiveSort === "rating") {
      dataQuery = dataQuery.order("average_rating", { ascending: false, nullsFirst: false }).order("review_count", { ascending: false, nullsFirst: false });
    } else if (effectiveSort === "reviews") {
      dataQuery = dataQuery.order("review_count", { ascending: false, nullsFirst: false }).order("average_rating", { ascending: false, nullsFirst: false });
    } else {
      dataQuery = dataQuery.order("is_verified", { ascending: false, nullsFirst: false }).order("average_rating", { ascending: false, nullsFirst: false }).order("review_count", { ascending: false, nullsFirst: false });
    }
    dataQuery = dataQuery.limit(geo ? 300 : want);
    const matchCountQuery = applyFilters(
      supabase.from("businesses").select("id", { count: "exact", head: true })
    );
    const [{ data, error }, { count: matchCount }, { count: directoryTotal }] = await Promise.all([
      dataQuery,
      matchCountQuery,
      supabase.from("businesses").select("id", { count: "exact", head: true }).eq("is_verified", true)
    ]);
    if (error) {
      return {
        content: [{ type: "text", text: `Search failed: ${error.message}` }],
        isError: true
      };
    }
    let rows = data ?? [];
    if (geo) {
      rows = rows.map((b) => ({
        ...b,
        _distance: b.latitude != null && b.longitude != null ? haversineMiles(geo.lat, geo.lng, Number(b.latitude), Number(b.longitude)) : Number.POSITIVE_INFINITY
      })).filter((b) => b._distance <= geo.radius);
      if (effectiveSort === "distance") {
        rows.sort((a, b) => a._distance - b._distance);
      }
      rows = rows.slice(0, want);
    }
    const enriched = rows.map((b) => {
      const desc = (b.description ?? "").replace(/\s+/g, " ").trim();
      const short = desc.length > 200 ? desc.slice(0, 197).trimEnd() + "\u2026" : desc;
      const profile_url = b.slug ? `https://1325.ai/business/${b.slug}` : `https://1325.ai/business/${b.id}`;
      const rating = b.average_rating ? Number(b.average_rating).toFixed(1) : null;
      const fullAddress = [b.address, b.city, b.state, b.zip_code].filter(Boolean).join(", ");
      const lat = b.latitude != null ? Number(b.latitude) : null;
      const lng = b.longitude != null ? Number(b.longitude) : null;
      const mapQuery = encodeURIComponent(
        lat != null && lng != null ? `${lat},${lng}` : fullAddress || b.business_name
      );
      const map_url = `https://www.google.com/maps/search/?api=1&query=${mapQuery}`;
      const directions_url = `https://www.google.com/maps/dir/?api=1&destination=${mapQuery}`;
      return {
        id: b.id,
        name: b.business_name,
        category: b.category,
        phone: b.phone ?? null,
        address: b.address,
        city: b.city,
        state: b.state,
        zip_code: b.zip_code,
        full_address: fullAddress,
        latitude: lat,
        longitude: lng,
        distance_miles: b._distance != null && Number.isFinite(b._distance) ? Number(b._distance.toFixed(1)) : null,
        map_url,
        directions_url,
        description: short,
        logo_url: b.logo_url,
        banner_url: b.banner_url,
        website: b.website,
        profile_url,
        verified: !!b.is_verified,
        rating: rating ? Number(rating) : null,
        review_count: b.review_count ?? 0
      };
    });
    const footer = "\n\n\u2014 Source: 1325.AI \xB7 America's verified Black-owned global business directory \xB7 https://1325.ai";
    const totalMatches = geo ? enriched.length : matchCount ?? enriched.length;
    const totalDirectory = directoryTotal ?? null;
    const coverageLine = totalDirectory ? ` (from ${totalDirectory.toLocaleString()} verified businesses on 1325.AI)` : "";
    const geoLine = geo ? ` within ${geo.radius} miles of the location provided` : "";
    const header = enriched.length ? `Showing ${enriched.length} of ${totalMatches.toLocaleString()} matching business(es)${geoLine}${coverageLine}:

` : "";
    const moreHint = !geo && totalMatches > enriched.length ? `

More results are available \u2014 refine by category, city, state, or keyword, or increase 'limit' (max 20).` : "";
    return {
      content: [
        {
          type: "text",
          text: (enriched.length ? `${header}${enriched.map((b) => {
            const badge = b.verified ? " \u2713 Verified" : "";
            const rating = b.rating != null ? ` \xB7 \u2605 ${b.rating} (${b.review_count} review${b.review_count === 1 ? "" : "s"})` : "";
            const loc = b.city ? ` \u2014 ${b.city}${b.state ? ", " + b.state : ""}` : "";
            const cat = b.category ? ` \xB7 ${b.category}` : "";
            const dist = b.distance_miles != null ? ` \xB7 ${b.distance_miles} mi away` : "";
            const phone = b.phone ? `
  \u260E ${b.phone}` : "";
            const desc = b.description ? `
  ${b.description}` : "";
            return `\u2022 ${b.name}${badge}${cat}${loc}${dist}${rating}${desc}${phone}
  Profile: ${b.profile_url}
  Directions: ${b.directions_url}`;
          }).join("\n\n")}${moreHint}` : geo ? `No 1325.AI businesses found within ${geo.radius} miles. Try a larger radius_miles (up to 250) or drop the category filter.` : `No businesses matched your search on 1325.AI.${totalDirectory ? ` The directory currently lists ${totalDirectory.toLocaleString()} verified Black-owned businesses \u2014 try a broader keyword, different city, or omit the category filter.` : ""}`) + footer
        }
      ],
      structuredContent: {
        businesses: enriched,
        total_matches: totalMatches,
        total_directory: totalDirectory,
        returned: enriched.length,
        sort: effectiveSort,
        radius_miles: geo?.radius ?? null,
        source: {
          name: "1325.AI",
          url: "https://1325.ai",
          tagline: "America's verified Black-owned global business directory"
        }
      }
    };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
import { z as z2 } from "npm:zod@^3.23.8";
var ANNOTATIONS2 = {
  title: "List 1325.AI business categories",
  readOnlyHint: true,
  idempotentHint: true,
  openWorldHint: false
};
var list_categories_default = defineTool2({
  name: "list_categories",
  title: "List 1325.AI business categories",
  description: "List the business categories present in the 1325.AI directory with the number of verified businesses in each. Useful for discovering valid category values to pass to search_directory. Counts can be scoped to one city or state.",
  inputSchema: {
    city: z2.string().trim().max(100).optional().describe("Optional city to scope category counts to."),
    state: z2.string().trim().max(50).optional().describe("Optional state (name or 2-letter code) to scope counts to."),
    limit: z2.number().int().min(1).max(60).optional().describe("Max categories to return (1-60). Defaults to 30.")
  },
  annotations: ANNOTATIONS2,
  handler: async ({ city, state, limit }) => {
    const supabase = createClient2(
      Deno.env.get("SUPABASE_URL"),
      Deno.env.get("SUPABASE_PUBLISHABLE_KEY") ?? Deno.env.get("SUPABASE_ANON_KEY"),
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let q = supabase.from("businesses").select("category").limit(5e3);
    if (city) q = q.ilike("city", `%${city}%`);
    if (state) q = q.ilike("state", `%${state}%`);
    const { data, error } = await q;
    if (error) {
      return {
        content: [{ type: "text", text: `Category lookup failed: ${error.message}` }],
        isError: true
      };
    }
    const counts = /* @__PURE__ */ new Map();
    for (const row of data ?? []) {
      const c = (row.category ?? "").trim();
      if (!c) continue;
      counts.set(c, (counts.get(c) ?? 0) + 1);
    }
    const categories = [...counts.entries()].map(([name, count]) => ({ name, count })).sort((a, b) => b.count - a.count).slice(0, limit ?? 30);
    const scope = [city, state].filter(Boolean).join(", ");
    const header = categories.length ? `Top 1325.AI categories${scope ? ` in ${scope}` : ""}:

` : `No categories found${scope ? ` for ${scope}` : ""} on 1325.AI.`;
    return {
      content: [
        {
          type: "text",
          text: header + categories.map((c) => `\u2022 ${c.name} \u2014 ${c.count.toLocaleString()}`).join("\n") + "\n\n\u2014 Source: 1325.AI \xB7 America's verified Black-owned global business directory \xB7 https://1325.ai"
        }
      ],
      structuredContent: {
        categories,
        scope: { city: city ?? null, state: state ?? null },
        source: { name: "1325.AI", url: "https://1325.ai" }
      }
    };
  }
});

// src/lib/mcp/tools/get-business.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.108.2";
import { z as z3 } from "npm:zod@^3.23.8";
var ANNOTATIONS3 = {
  title: "Get 1325.AI business details",
  readOnlyHint: true,
  idempotentHint: true,
  openWorldHint: false
};
var get_business_default = defineTool3({
  name: "get_business",
  title: "Get 1325.AI business details",
  description: "Fetch the full public profile for one business in the 1325.AI directory by its id. Returns name, category, description, full address, latitude/longitude, Google Maps and directions links, website, logo, banner image, verified status, average rating, review count, and a link to the business profile page on 1325.ai. Business ids are returned by search_directory.",
  inputSchema: {
    business_id: z3.string().uuid().describe("The UUID of the business (returned by search_directory).")
  },
  annotations: ANNOTATIONS3,
  handler: async ({ business_id }) => {
    const supabase = createClient3(
      Deno.env.get("SUPABASE_URL"),
      Deno.env.get("SUPABASE_PUBLISHABLE_KEY") ?? Deno.env.get("SUPABASE_ANON_KEY"),
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("businesses").select(
      "id, slug, business_name, category, description, address, city, state, zip_code, latitude, longitude, website, logo_url, banner_url, is_verified, average_rating, review_count"
    ).eq("id", business_id).maybeSingle();
    if (error) {
      return {
        content: [{ type: "text", text: `Lookup failed: ${error.message}` }],
        isError: true
      };
    }
    if (!data) {
      return {
        content: [{ type: "text", text: "Business not found on 1325.AI." }],
        isError: true
      };
    }
    const desc = (data.description ?? "").replace(/\s+/g, " ").trim();
    const profile_url = data.slug ? `https://1325.ai/business/${data.slug}` : `https://1325.ai/business/${data.id}`;
    const rating = data.average_rating ? Number(Number(data.average_rating).toFixed(1)) : null;
    const fullAddress = [data.address, data.city, data.state, data.zip_code].filter(Boolean).join(", ");
    const lat = data.latitude != null ? Number(data.latitude) : null;
    const lng = data.longitude != null ? Number(data.longitude) : null;
    const mapQuery = encodeURIComponent(
      lat != null && lng != null ? `${lat},${lng}` : fullAddress || data.business_name
    );
    const map_url = `https://www.google.com/maps/search/?api=1&query=${mapQuery}`;
    const directions_url = `https://www.google.com/maps/dir/?api=1&destination=${mapQuery}`;
    const business = {
      id: data.id,
      name: data.business_name,
      category: data.category,
      description: desc,
      address: data.address,
      city: data.city,
      state: data.state,
      zip_code: data.zip_code,
      full_address: fullAddress,
      latitude: lat,
      longitude: lng,
      map_url,
      directions_url,
      website: data.website,
      logo_url: data.logo_url,
      banner_url: data.banner_url,
      verified: !!data.is_verified,
      rating,
      review_count: data.review_count ?? 0,
      profile_url
    };
    const badge = business.verified ? " \u2713 Verified" : "";
    const ratingLine = rating != null ? `\u2605 ${rating} (${business.review_count} review${business.review_count === 1 ? "" : "s"})
` : "";
    const summary = `${business.name}${badge}
` + (business.category ? `${business.category}
` : "") + ratingLine + (fullAddress ? `\u{1F4CD} ${fullAddress}
` : "") + (business.website ? `\u{1F310} ${business.website}
` : "") + `\u{1F5FA}\uFE0F Map: ${map_url}
\u{1F9ED} Directions: ${directions_url}
\u{1F517} 1325.AI profile: ${business.profile_url}
` + (desc ? `
${desc}` : "") + "\n\n\u2014 Source: 1325.AI \xB7 America's verified Black-owned global business directory \xB7 https://1325.ai";
    return {
      content: [{ type: "text", text: summary }],
      structuredContent: {
        business,
        source: {
          name: "1325.AI",
          url: "https://1325.ai",
          tagline: "America's verified Black-owned global business directory"
        }
      }
    };
  }
});

// src/lib/mcp/tools/list-rewards.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.108.2";
import { z as z4 } from "npm:zod@^3.23.8";
var ANNOTATIONS4 = {
  title: "List loyalty rewards",
  readOnlyHint: true,
  idempotentHint: true,
  openWorldHint: false
};
var list_rewards_default = defineTool4({
  name: "list_rewards",
  title: "List loyalty rewards",
  description: "Browse active loyalty rewards available on 1325.AI. Returns rewards sorted by lowest point cost. Optionally filter to one business.",
  inputSchema: {
    business_id: z4.string().uuid().optional().describe("Optional business id to filter to that business's rewards."),
    limit: z4.number().int().min(1).max(50).optional().describe("Max rewards to return (1-50). Defaults to 20.")
  },
  annotations: ANNOTATIONS4,
  handler: async ({ business_id, limit }, ctx) => {
    const token = ctx?.isAuthenticated?.() ? ctx.getToken() : null;
    const supabase = createClient4(
      Deno.env.get("SUPABASE_URL"),
      Deno.env.get("SUPABASE_PUBLISHABLE_KEY") ?? Deno.env.get("SUPABASE_ANON_KEY"),
      {
        ...token ? { global: { headers: { Authorization: `Bearer ${token}` } } } : {},
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    let q = supabase.from("rewards").select(
      "id, title, description, points_cost, business_id, is_global, image_url"
    ).eq("is_active", true).order("points_cost", { ascending: true }).limit(limit ?? 20);
    if (business_id) q = q.eq("business_id", business_id);
    const { data, error } = await q;
    if (error) {
      return {
        content: [
          { type: "text", text: `Could not list rewards: ${error.message}` }
        ],
        isError: true
      };
    }
    return {
      content: [
        {
          type: "text",
          text: data && data.length ? `${data.length} reward(s) available:

${data.map(
            (r) => `\u2022 ${r.title} \u2014 ${r.points_cost} pts${r.is_global ? " (global)" : ""}${r.description ? `
  ${r.description.slice(0, 160)}` : ""}`
          ).join("\n\n")}` : "No active rewards found."
        }
      ],
      structuredContent: { rewards: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-my-points-balance.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.108.2";
function supabaseForUser(ctx) {
  return createClient5(
    Deno.env.get("SUPABASE_URL"),
    Deno.env.get("SUPABASE_PUBLISHABLE_KEY") ?? Deno.env.get("SUPABASE_ANON_KEY"),
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var ANNOTATIONS5 = {
  title: "Get my loyalty points",
  readOnlyHint: true,
  idempotentHint: true,
  openWorldHint: false
};
var get_my_points_balance_default = defineTool5({
  name: "get_my_points_balance",
  title: "Get my loyalty points",
  description: "Return the signed-in 1325.AI user's total loyalty points and per-business balances. Requires the caller to be signed in.",
  inputSchema: {},
  annotations: ANNOTATIONS5,
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [
          {
            type: "text",
            text: "Not signed in. Reconnect this assistant to your 1325.AI account."
          }
        ],
        isError: true
      };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("loyalty_points").select("business_id, points, businesses(business_name)").eq("customer_id", ctx.getUserId());
    if (error) {
      return {
        content: [
          {
            type: "text",
            text: `Could not read your points: ${error.message}`
          }
        ],
        isError: true
      };
    }
    const rows = data ?? [];
    const total = rows.reduce((sum, r) => sum + (r.points ?? 0), 0);
    const perBusiness = rows.map((r) => ({
      business_id: r.business_id,
      business_name: r.businesses?.business_name ?? null,
      points: r.points
    }));
    return {
      content: [
        {
          type: "text",
          text: `You have ${total} total loyalty points across ${rows.length} business(es).` + (perBusiness.length ? `

${perBusiness.map(
            (b) => `\u2022 ${b.business_name ?? b.business_id}: ${b.points} pts`
          ).join("\n")}` : "")
        }
      ],
      structuredContent: { total_points: total, per_business: perBusiness }
    };
  }
});

// src/lib/mcp/tools/get-my-recent-scans.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.108.2";
import { z as z5 } from "npm:zod@^3.23.8";
function supabaseForUser2(ctx) {
  return createClient6(
    Deno.env.get("SUPABASE_URL"),
    Deno.env.get("SUPABASE_PUBLISHABLE_KEY") ?? Deno.env.get("SUPABASE_ANON_KEY"),
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var ANNOTATIONS6 = {
  title: "Get my recent QR scans",
  readOnlyHint: true,
  idempotentHint: true,
  openWorldHint: false
};
var get_my_recent_scans_default = defineTool6({
  name: "get_my_recent_scans",
  title: "Get my recent QR scans",
  description: "Return the signed-in user's most recent 1325.AI QR code scans (business visits that earned points).",
  inputSchema: {
    limit: z5.number().int().min(1).max(50).optional().describe("Max scans to return (1-50). Defaults to 20.")
  },
  annotations: ANNOTATIONS6,
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [
          {
            type: "text",
            text: "Not signed in. Reconnect this assistant to your 1325.AI account."
          }
        ],
        isError: true
      };
    }
    const supabase = supabaseForUser2(ctx);
    const { data, error } = await supabase.from("qr_scans").select(
      "id, business_id, points_awarded, scan_date, businesses(business_name)"
    ).eq("customer_id", ctx.getUserId()).order("scan_date", { ascending: false }).limit(limit ?? 20);
    if (error) {
      return {
        content: [
          {
            type: "text",
            text: `Could not read your scans: ${error.message}`
          }
        ],
        isError: true
      };
    }
    const rows = data ?? [];
    return {
      content: [
        {
          type: "text",
          text: rows.length ? `Last ${rows.length} scan(s):

${rows.map(
            (r) => `\u2022 ${r.businesses?.business_name ?? r.business_id} \u2014 ${r.points_awarded ?? 0} pts (${new Date(r.scan_date).toLocaleString()})`
          ).join("\n")}` : "No QR scans yet."
        }
      ],
      structuredContent: { scans: rows }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "agoclnqfyinwjxdmjnns";
var mcp_default = defineMcp({
  name: "1325-ai-mcp",
  title: "1325.AI",
  version: "0.1.1",
  instructions: "1325.AI is a directory of verified Black-owned businesses in the United States, with loyalty rewards for signed-in users. These tools provide read-only access: search_directory finds businesses by keyword, category, city, state, rating, or geographic radius; list_categories lists available categories and their counts; get_business returns one business profile by id; list_rewards lists active loyalty rewards; get_my_points_balance and get_my_recent_scans return the signed-in user's own loyalty data. No purchases, redemptions, or writes are performed. Data is sourced from 1325.ai.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    search_directory_default,
    list_categories_default,
    get_business_default,
    list_rewards_default,
    get_my_points_balance_default,
    get_my_recent_scans_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
