WITH src(business_name,category,address,city,state,phone,website,description,banner_url) AS (VALUES
('Numero Uno Beach House','Vacation Rental','1 C. Sta. Ana','San Juan','Puerto Rico','','','Oceanfront relaxed luxury meets adventure at Numero Uno Beach House, owned and managed by San Juan–born entrepreneur Damian Maldonado. Since acquiring and revitalizing the property in 2019, Maldonado has infused it with local flair—launching Kite Puerto Rico, refreshing the guest rooms and beachside restaurant, and creating a laid-back haven that’s deeply rooted in Puerto Rican community and culture.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/06/Numero-Uno-Beach-House-San-Juan-Puerto-Rico.jpg?fit=1024%2C683&ssl=1'),
('Hotel El Convento','Boutique Hotel','100 Calle del Cristo','San Juan','Puerto Rico','','https://expedia.stay22.com/blackhotelguide/N7e7xVdsBl','Once a Carmelite convent dating back to 1651, Hotel El Convento is now a luxurious boutique hotel blending Old World charm with modern indulgence.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/06/Hotel-El-Convento-12.jpg?fit=1024%2C683&ssl=1'),
('Hyatt Regency Atlanta Perimeter at Villa Christina','Hotel','4000 Summit Blvd','Atlanta','GA','','https://expedia.stay22.com/blackhotelguide/luBFEefuaS','Tucked away in a serene, tree-lined setting, the Hyatt Regency Atlanta Perimeter combines sophisticated luxury with Southern charm. With a focus on personalized service and upscale accommodations, it’s an ideal retreat for business travelers and vacationers alike.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/01/hyatt-regency-atlanta-1.jpg?fit=1000%2C563&ssl=1'),
('Courtyard by Marriott Atlanta Buckhead','Hotel','3332 Peachtree Road NE','Atlanta','GA','','https://expedia.stay22.com/blackhotelguide/Y0P8C55lgr','This black-owned hotel in Atlanta Georgia is located in the upscale Buckhead neighborhood and offers a stylish and convenient stay for business and leisure travelers alike. With contemporary accommodations, thoughtful amenities, and easy access to top shopping, dining, and entertainment.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/01/Courtyard-by-Marriott-Atlanta-Buckhead-guestroom.jpg?fit=1024%2C683&ssl=1'),
('Courtyard by Marriott Chicago Magnificent Mile','Hotel','165 E Ontario St','Chicago','IL','','https://expedia.stay22.com/blackhotelguide/dAHBfbrFAI','Modern Comfort in the Heart of Chicago’s Magnificent Mile. This black-owned hotel offers a perfect blend of comfort, style, and convenience, making it an ideal choice for leisure and business travelers alike.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/01/exterior-23.jpg?fit=1200%2C800&ssl=1'),
('The Wade, Chicago','Hotel','644 N Lake Shore Dr','Chicago','IL','','https://expedia.stay22.com/blackhotelguide/_cA-mLmJIn','With its prime location along Chicago’s scenic waterfront, The Wade (formerly the W Lakeshore) is where bold design meets luxurious comfort. This sleek, high-energy hotel is managed by Pyramid Global Hospitality, a premier hospitality company. The Wade offers stunning views of Lake Michigan, chic accommodations, and a vibrant social scene, making it a go-to destination for travelers looking to stay in style.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/05/The-Wade-Hotel-Chicago-7.jpg?fit=1024%2C683&ssl=1'),
('Residence Inn by Marriott Chicago Naperville/Warrenville','Hotel','28500 Bella Vista Parkway','Warrenville','IL','','https://expedia.stay22.com/blackhotelguide/nvUeJIZEA4','Experience the perfect blend of comfort and convenience at the Residence Inn Chicago Naperville/Warrenville. Located in the heart of the western suburbs, this extended-stay hotel offers a home-like atmosphere with modern amenities designed for both business and leisure travelers.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/01/exterior-29.jpg?fit=1200%2C800&ssl=1'),
('Courtyard by Marriott Chicago Midway Airport','Hotel','6610 S. Cicero Avenue','Chicago','IL','','https://expedia.stay22.com/blackhotelguide/lndQq_AP2k','Convenience and Comfort, Just Minutes from Midway. Experience the perfect blend of comfort and convenience at the black-owned hotel in Chicago. Located just a mile from Chicago Midway International Airport, this modern hotel offers thoughtful amenities and a welcoming atmosphere for business and leisure travelers alike.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/01/exterior-2-2.jpg?fit=1200%2C800&ssl=1'),
('Hilton Garden Inn Chicago / Midway Airport','Hotel','6530 S Cicero Ave','Bedford Park','IL','','','This black-owned hotel in Chicago is located just two blocks from Chicago Midway International Airport. The Hilton Garden Inn offers modern amenities, spacious rooms, on-site dining, an indoor pool, and complimentary airport shuttle service.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/01/exterior-27.jpg?fit=1023%2C682&ssl=1'),
('Wyndham New Orleans French Quarter','Hotel','124 Royal St','New Orleans','LA','','','A black-owned hotel in the vibrant heart of the French Quarter offering historic charm and contemporary convenience, with spacious accommodations and easy access to top attractions.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/01/lobby-44.jpg?fit=1200%2C799&ssl=1'),
('The Hubbard Mansion','B&B','3535 St Charles Ave','New Orleans','LA','Not provided','https://www.hubbardmansion.com/','Located on the historic St. Charles Avenue streetcar line, The Hubbard Mansion is a luxurious Black-owned bed and breakfast that captures the elegance of Old New Orleans with the warmth of Southern hospitality. This five-suite Greek Revival-style mansion offers guests a refined and culturally rich experience just minutes from the French Quarter.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/03/The-Hubbard-Mansion-New-Orleans-1.jpg?fit=1000%2C1333&ssl=1'),
('Hilton Garden Inn New Orleans Convention Center','Hotel','1001 S Peters St','New Orleans','LA','','https://expedia.stay22.com/blackhotelguide/Iv4mkUp0_z','Located in the heart of New Orleans’ Warehouse District, Hilton Garden Inn New Orleans Convention Center offers a stylish and convenient stay just steps from the Ernest N. Morial Convention Center. This Black-owned hotel is perfect for business travelers, festival-goers, and visitors looking to experience the vibrant culture, food, and music of the Crescent City.','https://blackhotelguide.com/wp-content/uploads/2020/01/3-color-268-png-vr-1.png'),
('Royal Palm South Beach Miami','Hotel','1545 Collins Avenue','Miami Beach','FL','','https://expedia.stay22.com/blackhotelguide/ofUw3qO_9Q','A historic hotel with modern luxury, located in the heart of Miami Beach’s Art Deco District, blending historic charm with contemporary amenities. Originally developed by The Peebles Corporation, represents significant cultural and hospitality heritage as one of the first major Black-developed luxury resorts in the U.S.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2026/04/Royal-Palm-South-Beach-Miami-beach-2.jpg?fit=1000%2C667&ssl=1'),
('Dunns Josephine Hotel','Hotel','Overtown, Miami','Miami','FL','','https://expedia.stay22.com/blackhotelguide/vX-5EDkw_i','A historic boutique hotel that honors the legacy of the Harlem Renaissance and Miami’s Black history, providing a haven for Black entertainers during the segregation era.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/03/street-view-1-1.jpg?resize=765%2C1020&ssl=1'),
('Ma Margaret’s House Bed & Breakfast','Bed & Breakfast','249 Greenfield Rd','Reedville','VA','','https://booking.stay22.com/blackhotelguide/40Y2SxNtAH','A lovingly restored 1914 home transformed into a luxurious countryside haven. This charming Black-owned B&B blends antique character with modern comforts, creating an intimate retreat near Chesapeake Bay.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/05/Ma-Margarets-House.jpg?fit=1000%2C667&ssl=1'),
('The Old No. 77 Hotel & Chandlery','Boutique Hotel','535 Tchoupitoulas St','New Orleans','LA','Not provided','','Art, soul, and Southern charm—New Orleans reimagined. The Old No. 77 Hotel & Chandlery delivers a soulful, design-driven stay infused with local art, culture, and culinary creativity. This historic property has been transformed into a boutique destination that honors the city’s layered past.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/05/The-Old-No-77-Hotel-Chandlery-10.jpg?fit=1024%2C683&ssl=1'),
('The Shores Resort & Spa','Resort','2637 S Atlantic Ave','Daytona Beach Shores','FL','','','Oceanfront elegance with Southern charm in Daytona Beach Shores. The Shores Resort & Spa is a luxe beachfront retreat that blends coastal sophistication with laid-back Floridian warmth, offering stylish rooms, ocean-inspired spa, dining, and direct beach access.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/05/The-Shores-Resort-Spa-13.jpg?fit=1024%2C683&ssl=1'),
('Parador Villas Del Mar Hau','Parador','Sector Bajuras Rd 466 Montones Beach','Isabela','00662','','https://expedia.stay22.com/blackhotelguide/yWXI3WNZ7t','Located on the golden shores of Playa Jobos, Parador Villas Del Mar Hau is a native Puerto Rican–owned gem offering laid-back tropical living with unbeatable beach access. Offering private villas and rooms with ocean or garden views, it features an outdoor pool, an onsite restaurant, and numerous activities for guests.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/06/parador-villas-del-mar.jpg?fit=1000%2C750&ssl=1'),
('Parador Maunacaribe Maunabo','Parador (Country Inn)','PR-901','Maunabo','Puerto Rico','','','Nestled along the serene southeastern coast of Puerto Rico, Parador Maunacaribe in Maunabo is a native Puerto Rican owned resort offering an idyllic beachfront retreat away from the bustling tourist hubs. This locally owned parador embodies the warmth of Boricua hospitality, providing guests with a peaceful setting, ocean views, and an authentic island experience on a budget.','https://blackhotelguide.com/wp-content/uploads/2025/02/parador-maunacaribe.jpg'),
('SeaGarden Beach Resort','Resort','N/A','Montego Bay','Jamaica','N/A','','Family-run all-inclusive resort offering guests an authentic Jamaican stay rooted in warmth, culture, and personalized service.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2026/02/SeaGarden-Beach-Resort-%E2%80%94-Montego-Bay-Jamaica-seagarden-beach-resort.jpg?fit=1000%2C664&ssl=1')
)
INSERT INTO public.businesses (name, business_name, category, address, city, state, phone, website, description, banner_url, owner_id, listing_status, is_verified)
SELECT s.business_name, s.business_name, s.category, NULLIF(s.address,''), NULLIF(s.city,''), NULLIF(s.state,''), NULLIF(s.phone,''), NULLIF(s.website,''), NULLIF(s.description,''), NULLIF(s.banner_url,''), 'bd72a75e-1310-4f40-9c74-380443b09d9b'::uuid, 'live', true
FROM src s
WHERE NOT EXISTS (SELECT 1 FROM public.businesses b WHERE lower(regexp_replace(b.business_name,'[^A-Za-z0-9]+','','g')) = lower(regexp_replace(s.business_name,'[^A-Za-z0-9]+','','g')));