WITH src(business_name,category,address,city,state,phone,website,description,banner_url) AS (VALUES
('The Westin Grand Cayman Seven Mile Beach Resort & Spa','Resort','Seven Mile Beach','Grand Cayman','Cayman Islands','(345) 945-3800','https://expedia.com/affiliates/seven-mile-beach-hotels-the-westin-grand-cayman-seven-mile-beach-resort-spa.zhrUUxb','This black-owned resort offers a luxurious escape on Seven Mile Beach with stunning beachfront access, exceptional dining, and world-class amenities. Ideal for families, couples, and travelers seeking a tropical getaway.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/01/westin-grand-cayman-pool.jpg?fit=1200%2C800&ssl=1'),
('House of Waine','Hotel','Masai Lane, off Bogani Rd','Nairobi','','','https://expedia.com/affiliates/nairobi-hotels-house-of-waine.Z5JKXV8','A Black-owned, family-run boutique hotel that radiates warmth, charm, and luxury, providing personalized service, lush gardens, and easy access to Nairobi’s top attractions.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/03/House-of-Waine-10.jpg?fit=574%2C768&ssl=1'),
('The Social House','Hotel','154 James Gichuru Road','Nairobi','','','https://expedia.com/affiliates/nairobi-hotels-the-social-house-nairobi.vBVnRy1','Located in the heart of Lavington, Nairobi, The Social House is a dynamic, Black-owned boutique hotel known for its eclectic design, vibrant atmosphere, and innovative dining experiences. Blending a relaxed, creative vibe with modern luxury, it offers a refreshing take on hospitality, catering to travelers seeking a unique, authentic experience in Kenya’s capital.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/03/The-Social-House-1.jpg?fit=549%2C768&ssl=1'),
('Birmingham Marriott','Hotel','3590 Grandview Pkwy','Birmingham','AL','N/A','https://expedia.com/affiliates/birmingham-hotels-marriott-birmingham.wSAid5J','Experience Southern hospitality and modern elegance at the African American owned hotel in Birmingham Alabama, Brimingham-Marriott, an upscale hotel nestled in the heart of Alabama’s bustling business district. Perfectly suited for both leisure and business travelers, the hotel offers sophisticated accommodations and an array of premium amenities to make your stay exceptional.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/01/exterior-1-2.jpg?fit=1200%2C800&ssl=1'),
('Frederick Douglass Museum and Cultural Center','Museum','3200 Wayman Avenue','Highland Beach','MD','N/A','https://www.fdmcc.org/','Preserving the Legacy of a Freedom Fighter in Highland Beach, the Frederick Douglass Museum and Cultural Center stands as a powerful tribute to the enduring legacy of Frederick Douglass, showcasing African American history and culture.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/05/Frederick_Douglass_House-1.jpg?fit=960%2C638&ssl=1'),
('Royal Senchi Hotel & Resort','Resort','Ferry Road','Akosombo','','','https://expedia.com/affiliates/akosombo-hotels-the-royal-senchi-resorthotel.NC10Qft','Ghana''s Riverside Oasis offering a luxurious blend of modern sophistication and traditional Ghanaian charm. Celebrated for its lush surroundings, warm hospitality, and exquisite facilities, making it a sought-after destination for relaxation and romance.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/03/Royal-Senchi-Resort.jpg?fit=1024%2C682&ssl=1'),
('Courtyard Birmingham Downtown at UAB','Hotel','1820 5th Avenue South','Birmingham','Alabama','','https://expedia.com/affiliates/birmingham-hotels-courtyard-birmingham-downtown-at-uab.iGwEyq7','Located in the heart of Birmingham’s Medical District and steps from the University of Alabama at Birmingham (UAB), this hotel offers modern convenience in one of Alabama’s most historically significant cities. Managed by Pyramid Global Hospitality under Black executive leadership, it features modern guest rooms and easy access to cultural landmarks.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2026/02/Courtyard-by-Marriott-Birmingham-Downtown-at-UAB-guestroom1.jpg?fit=1024%2C683&ssl=1'),
('Travellers Beach Resort','Resort','Norman Manley Boulevard','Negril','Jamaica','','https://expedia.com/affiliates/negril-hotels-travellers-beach-resort.tSyfpMI','A proudly family-run, Black-owned property offering guests an authentic and welcoming Caribbean experience along the world-famous Seven Mile Beach in Negril.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2026/02/Travellers-Beach-Resort-%E2%80%94-Negril-Jamaica-on-7-mile-beach.jpg?fit=1024%2C683&ssl=1'),
('The Sandman Santa Rosa Sonoma','Hotel','3421 Cleveland Avenue','Santa Rosa','California','','https://expedia.com/affiliates/santa-rosa-hotels-the-sandman.vXidDmc','Retro-modern boutique hotel offering a relaxed Wine Country vibe with modern comforts. Ideal for travelers seeking a stylish yet unpretentious base in Northern California''s Wine Country.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2026/02/The-Sandman-Santa-Rosa-Sonoma-%E2%80%94-an-Ascend-Collection-Hotel.jpg?fit=1024%2C683&ssl=1'),
('Wilks Bay Resort','Boutique Resort','Wilks Bay','Port Antonio','Portland','','','Celebrated Black-Owned Boutique Resort with Island Elegance, offering a peaceful getaway with luxury, personalized service, and a vibrant cultural experience.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2026/02/the-resort-at-wilks-bay.jpg?fit=1000%2C750&ssl=1'),
('The Wigwam','Resort','300 East Wigwam Boulevard','Phoenix','Arizona','','https://expedia.com/affiliates/phoenix-hotels-the-wigwam.iy4UIor','Historic Desert Resort with Black Executive Hospitality Leadership, known for casita-style accommodations, championship golf, and classic Southwestern charm.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2026/02/The-Wigwam-family-fun.jpg?fit=1000%2C1500&ssl=1'),
('Hyatt House Washington DC / Convention Center','Hotel','899 O St NW','Washington D.C.','DC','','','Black-developed extended-stay comfort in the heart of the nation’s capital. Located near the Walter E. Washington Convention Center, the hotel is designed for both short visits and longer stays, offering spacious accommodations with residential-style amenities in a vibrant downtown setting.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2026/03/Hyatt-House-Washington-DC-Convention-Center-Washington-D.C.-.jpg?fit=1024%2C683&ssl=1'),
('Quality Inn Memphis Northeast, TN','Hotel','2855 Old Austin Peay Hwy','Memphis','TN','','https://expedia.com/affiliates/memphis-hotels-quality-inn.Oyo7DTu','Located in the heart of the Bluff City, Quality Inn Memphis Northeast is a Black-owned gem redefining affordable comfort and service. This hotel offers updated interiors, friendly service, and proximity to major Memphis attractions, delivering value for travelers who support Black-owned lodging businesses.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/06/Quality-Inn-Memphis-Northeast-TN-6.jpg?fit=1024%2C683&ssl=1'),
('Africatown Heritage House','Cultural Center/Museum','2465 Mobile Street','Theodore','AL','','https://africatownhpf.org/','Africatown Heritage House is a modern cultural center and museum that serves as the central hub for understanding the journey of the Clotilda survivors and the community they built, highlighting the legacy of their resilience and cultural preservation.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2026/03/Africatown-Africatown-Heritage-House-exhibits.jpg?fit=1200%2C800&ssl=1'),
('The Kendall Hotel at Engine 7 Firehouse','Hotel','','Cambridge','Massachusetts','','','Housed in a beautifully restored 19th-century firehouse in the heart of Kendall Square, The Kendall Hotel blends historic character with boutique comfort and a distinctly local feel.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2026/02/The-Kendall-Hotel-Street-View.jpg?fit=644%2C768&ssl=1'),
('Cambria Hotel Philadelphia Downtown City Center','Hotel','5501 Germantown Ave','Philadelphia','PA','(215) 205-4324','','Located along Philadelphia’s iconic Avenue of the Arts, Cambria Hotel Philadelphia Downtown City Center delivers a modern, design-forward stay in the heart of the city’s cultural and entertainment district. The hotel is professionally managed by Pyramid Global Hospitality, making it a Black-managed hotel under Black executive leadership.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2026/02/Cambria-Hotel-Philadelphia-Downtown-City-Center-Exterior-%E2%80%94-Philadelphia-Pennsylvania.jpg?resize=653%2C199&ssl=1'),
('Captain Farris House Bed & Breakfast','Bed & Breakfast','308 Old Main St','South Yarmouth','MA','','https://expedia.com/affiliates/south-yarmouth-hotels-the-captain-farris-house-bb.3lGtYQI','Charming Cape Cod Retreat offering romantic ambiance, elegant décor, and warm hospitality. Ideal for couples, cultural travelers, or those just seeking a peaceful escape.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/09/Captain-Farris-House-Bed-Breakfast.jpg?fit=1024%2C683&ssl=1'),
('Wyndham Philadelphia Historic District','Hotel','701 Arch Street','Philadelphia','PA','(215) 574-0380','https://www.aampmuseum.org/','One of the most convenient hotels near the African American Museum in Philadelphia, the Wyndham Philadelphia Historic District places you within easy walking distance of AAMP, the Liberty Bell, and Independence Hall. This full-service hotel blends modern comfort with an unbeatable Old City location.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/02/exterior-1-4.jpg?resize=900%2C639&ssl=1'),
('Whitney Plantation','Museum','5099 LA-18','Edgard','LA','','https://whitneyplantation.org/','Located along Louisiana’s historic River Road, Whitney Plantation African American Museum stands as a powerful memorial to the lives of the enslaved people who once toiled on its grounds. Unlike many other plantation tours that focus on grandeur and architecture, Whitney Plantation is dedicated to telling the unfiltered story of slavery in America.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/02/Whitney-Plantation3.jpg?fit=1360%2C1020&ssl=1'),
('Villa 37 On Westridge','Villa','37 Westridge Road','uMhlanga','KwaZulu-Natal','','https://www.airbnb.com/rooms/26211426','A stylish coastal retreat with privacy, space, and elevated comfort in Durban. Villa 37 On Westridge is a luxury villa offering a private, design-forward escape just minutes from the beach and city attractions.','https://blackhotelguide.com/wp-content/uploads/2020/01/3-color-268-png-vr-1.png')
)
INSERT INTO public.businesses (name, business_name, category, address, city, state, phone, website, description, banner_url, owner_id, listing_status, is_verified)
SELECT s.business_name, s.business_name, s.category, NULLIF(s.address,''), NULLIF(s.city,''), NULLIF(s.state,''), NULLIF(s.phone,''), NULLIF(s.website,''), NULLIF(s.description,''), NULLIF(s.banner_url,''), 'bd72a75e-1310-4f40-9c74-380443b09d9b'::uuid, 'live', true
FROM src s
WHERE NOT EXISTS (SELECT 1 FROM public.businesses b WHERE lower(regexp_replace(b.business_name,'[^A-Za-z0-9]+','','g')) = lower(regexp_replace(s.business_name,'[^A-Za-z0-9]+','','g')));