
-- Review response drafts generated by Kayla
CREATE TABLE public.kayla_review_drafts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  review_id UUID NOT NULL,
  business_id UUID NOT NULL,
  draft_response TEXT NOT NULL,
  sentiment TEXT DEFAULT 'neutral',
  status TEXT NOT NULL DEFAULT 'pending',
  approved_at TIMESTAMPTZ,
  approved_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.kayla_review_drafts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Business owners can view their drafts"
  ON public.kayla_review_drafts FOR SELECT TO authenticated
  USING (business_id IN (SELECT id FROM businesses WHERE owner_id = auth.uid()));

CREATE POLICY "Business owners can update their drafts"
  ON public.kayla_review_drafts FOR UPDATE TO authenticated
  USING (business_id IN (SELECT id FROM businesses WHERE owner_id = auth.uid()));

CREATE POLICY "Service role can insert drafts"
  ON public.kayla_review_drafts FOR INSERT TO service_role
  WITH CHECK (true);

CREATE INDEX idx_kayla_review_drafts_business ON public.kayla_review_drafts(business_id);
CREATE INDEX idx_kayla_review_drafts_status ON public.kayla_review_drafts(status);

-- B2B match suggestions by Kayla
CREATE TABLE public.kayla_b2b_matches (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  buyer_business_id UUID NOT NULL,
  supplier_business_id UUID NOT NULL,
  need_id UUID,
  capability_id UUID,
  match_reason TEXT NOT NULL,
  match_score NUMERIC DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'suggested',
  notified_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.kayla_b2b_matches ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Involved businesses can view matches"
  ON public.kayla_b2b_matches FOR SELECT TO authenticated
  USING (
    buyer_business_id IN (SELECT id FROM businesses WHERE owner_id = auth.uid())
    OR supplier_business_id IN (SELECT id FROM businesses WHERE owner_id = auth.uid())
  );

CREATE POLICY "Service role can insert matches"
  ON public.kayla_b2b_matches FOR INSERT TO service_role
  WITH CHECK (true);

-- Content generated by Kayla (social posts, promo copy)
CREATE TABLE public.kayla_generated_content (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  business_id UUID NOT NULL,
  content_type TEXT NOT NULL DEFAULT 'social_post',
  content TEXT NOT NULL,
  platform TEXT DEFAULT 'general',
  status TEXT NOT NULL DEFAULT 'draft',
  published_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.kayla_generated_content ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Business owners can view their content"
  ON public.kayla_generated_content FOR SELECT TO authenticated
  USING (business_id IN (SELECT id FROM businesses WHERE owner_id = auth.uid()));

CREATE POLICY "Business owners can update their content"
  ON public.kayla_generated_content FOR UPDATE TO authenticated
  USING (business_id IN (SELECT id FROM businesses WHERE owner_id = auth.uid()));

CREATE POLICY "Service role can insert content"
  ON public.kayla_generated_content FOR INSERT TO service_role
  WITH CHECK (true);

-- Profile quality scores
CREATE TABLE public.kayla_profile_scores (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  business_id UUID NOT NULL UNIQUE,
  score INTEGER NOT NULL DEFAULT 0,
  max_score INTEGER NOT NULL DEFAULT 100,
  breakdown JSONB DEFAULT '{}'::jsonb,
  tips JSONB DEFAULT '[]'::jsonb,
  last_calculated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.kayla_profile_scores ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can view profile scores"
  ON public.kayla_profile_scores FOR SELECT TO authenticated
  USING (true);

CREATE POLICY "Service role can upsert scores"
  ON public.kayla_profile_scores FOR INSERT TO service_role
  WITH CHECK (true);

CREATE POLICY "Service role can update scores"
  ON public.kayla_profile_scores FOR ALL TO service_role
  USING (true);

CREATE INDEX idx_kayla_profile_scores_business ON public.kayla_profile_scores(business_id);
CREATE INDEX idx_kayla_profile_scores_score ON public.kayla_profile_scores(score DESC);
