WITH src(business_name,category,address,city,state,phone,website,description,banner_url) AS (VALUES
('The Florida Aquarium Ticket','Attraction','701 Channelside Drive','Tampa','FL','','https://gyg.me/p8208A6Q','Explore one of the top-rated aquariums in the country with this ticket, providing access to over 9,000 aquatic animals and interactive experiences.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/07/The-Florida-Aquarium-Ticket.jpg?fit=720%2C480&ssl=1'),
('La Piraña Lechonera','Food Trailer','766 E 152nd St','Bronx','NY','(347) 609-9714','https://lechoneralapirana.setrush.net/','La Piraña Lechonera is a Puerto Rican food trailer located in NYC, South Bronx, New York, known for its authentic lechón (roast pork) and traditional Puerto Rican dishes.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/06/La-Pirana-Lechonera-%E2%80%93-South-Bronx-NY-4.jpg?fit=862%2C1000&ssl=1'),
('188 Bakery Cuchifritos, NYC','Restaurant','158 E 188th St','Bronx','NY','(718) 367-4500','','An NYC staple serving bold Puerto Rican and Dominican flavors since 1971. A beloved fixture for over 50 years, this family-run eatery has earned national acclaim—including a coveted spot on the New York Times’ Top 100 Best Restaurants list—thanks to its unapologetically authentic dishes and vibrant street-corner energy. Whether you’re a local or a hungry traveler seeking soulful Latin Caribbean comfort food, this iconic cuchifrito joint delivers the goods with every bite.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/06/188-Bakery-Cuchifritos-NYC.jpg?fit=750%2C1000&ssl=1'),
('Puerto Criollo Restaurant','Restaurant','360 C. Tetuán','San Juan','','(787)-303-0016','https://puerto-criollo.restaurants-world.com/','A native Puerto Rican-owned celebration of island flavors in historic San Juan. Known for its signature mofongo, fresh seafood, and slow-roasted pork.','https://blackhotelguide.com/wp-content/uploads/2020/01/3-color-268-png-vr-1.png'),
('Taqueria El Sabor del Parque','Restaurant','Near Patterson Park','Baltimore','MD','(410) 558-0747','https://www.taqueriaelsabordelparque.com/','Authentic Mexican street food bursting with sabor in the heart of Baltimore.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/08/Taqueria-El-Sabor-del-Parque-Baltimore-MD.jpg?fit=750%2C1000&ssl=1'),
('Swan, Restaurant, Miami','Restaurant','90 NE 39th St','Miami','FL','','https://swanmiami.com/press/miamis-in-vogue-restaurants/','Chic Dining by Pharrell Williams in Miami. Nestled in Miami’s trendy Design District, Swan is a sophisticated dining hotspot co-owned by music and fashion icon Pharrell Williams. Known for its elegant ambiance, globally inspired cuisine, and vibrant social scene, this restaurant blends culinary artistry with Miami’s signature glamour.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/02/swan-6.jpg?fit=1000%2C1500&ssl=1'),
('BBQ Jones','Restaurant','6706 Kaw Dr','Kansas City','KS','(855) 752-7227','https://www.jonesbbqkc.com/','Authentic Kansas City BBQ with a Black-Owned Legacy. Located in the heart of Kansas City, BBQ Jones is a must-visit destination for lovers of true, slow-smoked barbecue. This Black-owned establishment blends family traditions, bold flavors, and a passion for hospitality to create a dining experience that keeps customers coming back for more.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/02/outside-view.jpg?fit=382%2C510&ssl=1'),
('Burdell, California','Restaurant','4640 Telegraph Ave','Oakland','CA','(510) 239-9287','https://www.burdelloakland.com/','At Burdell, Chef Geoff Davis channels the rich legacy of African American culinary tradition into a bold and modern expression of soul food. Named after his grandmother, this refined-yet-homey eatery in Oakland’s Temescal neighborhood is where memory meets innovation, offering modern interpretations of Black Southern and soul food classics.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/08/Burdell-California-1.jpg?fit=1000%2C698&ssl=1'),
('Longevity Wines','Winery','2271 S Vasco Rd Ste B','Livermore','CA','(925) 443-9463','https://www.longevitywines.com/','Award-Winning, Family-Run Black-Owned Winery in the Heart of Livermore Valley','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/08/Longevity-Wines-Livermore-CA.jpg?fit=750%2C1000&ssl=1'),
('Renaissance Fort Lauderdale West Hotel','Hotel','1230 S Pine Island Rd','Plantation','FL',',','https://expedia.com/affiliates/fort-lauderdale-hotels-renaissance-fort-lauderdale-plantation-hotel.CdQhNip','This black-owned upscale hotel features stylish accommodations, exceptional dining, and easy access to attractions like Sawgrass Mills, Hard Rock Casino, and the Fort Lauderdale-Hollywood International Airport. Ideal for business or leisure travelers.','https://blackhotelguide.com/wp-content/uploads/2020/01/3-color-268-png-vr-1.png'),
('Je T’aime Patisserie','Pastry Shop','471 Marcus Garvey Blvd','Brooklyn','NY','(718)-400-8730','https://www.jetaimebk.com/','A Parisian Escape in Brooklyn bringing the flavors of Paris with a unique twist focused on community and inclusivity, offering exquisite pastries and a welcoming atmosphere.','https://blackhotelguide.com/wp-content/uploads/2020/01/3-color-268-png-vr-1.png'),
('Berimbau Brazilian Kitchen','Restaurant','3 Carmine St','New York','NY','(212) 401-0021','https://www.berimbaunyc.com/','A vibrant and intimate restaurant in NYC’s West Village offering an authentic taste of Brazilian cuisine with a cozy atmosphere, famous for dishes like Feijoada, Moqueca, and Caipirinhas.','https://blackhotelguide.com/wp-content/uploads/2020/01/3-color-268-png-vr-1.png'),
('Yellow Block Bed & Breakfast','Bed & Breakfast','208 Quincy St','Brooklyn','NY','','https://expedia.com/affiliates/new-york-hotels-yellow-block-bnb.pu7KlnS','A Black-Owned Brooklyn Gem for Group Getaways. Yellow Block BnB is a premier Black-owned bed and breakfast in Brooklyn, New York that offers a unique blend of historic charm and modern comfort. Founded in 2011, it features 8 bedrooms and 5 bathrooms, accommodating up to 25 guests.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/05/Yellow-Block-Bed-Breakfast-3.jpg?fit=2080%2C1388&ssl=1'),
('The Soul Spot','Restaurant','302 Atlantic Ave.','Brooklyn','NY','(718) 596-9933','https://www.thesoulspot.com','Located in the heart of Brooklyn, The Soul Spot is a beloved dining destination offering a soulful taste of Southern and Caribbean cuisine. Nestled in the bustling Boerum Hill neighborhood, this Black-owned restaurant has built a loyal following thanks to its hearty, flavorful dishes and warm, welcoming atmosphere.','https://blackhotelguide.com/wp-content/uploads/2020/01/3-color-268-png-vr-1.png'),
('Regards, Restaurant','Restaurant','547 Congress St','Portland','ME','(207) 747-5940','https://www.regardsmaine.com/','Modern American Dining with Cuban Roots in the Heart of Portland, blending modern American cuisine with vibrant Cuban influences, showcasing an ever-evolving menu inspired by seasonal New England ingredients.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/08/Regards-Restaurant-Portland-ME-6.jpg?fit=750%2C1000&ssl=1'),
('AltaToro, Pan Latin Flavors','Restaurant','33 Peachtree Pl NE','Atlanta','GA','(470) 995-8676','https://altatoro.com/','Bold Latin flavors with a global twist in the heart of Midtown Atlanta. AltaToro reimagines classic dishes with bold creativity, offering a vibrant dining experience with a stylish décor and an inventive menu featuring dishes from Peru, Mexico, Argentina, and the Caribbean.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/06/AltaToro-1.jpg?fit=356%2C356&ssl=1'),
('Negril Village Restaurant','Restaurant','70 W 3rd St','New York','NY','(212) 477-2804','http://www.negrilvillage.com','Simple elegance meets authentic Jamaican cuisine in a vibrant atmosphere. Known for warm hospitality and bold flavors. Offers indoor and outdoor seating, full bar, vegetarian options, and event hosting. Perfect for casual meals and special celebrations.','https://blackhotelguide.com/wp-content/uploads/2020/01/3-color-268-png-vr-1.png'),
('9 Mile Station','Restaurant','675 Ponce De Leon Ave NE','Atlanta','GA','(770) 999-1532','https://9milestation.com/','A Black-owned rooftop beer garden and restaurant offering panoramic skyline views and a refined twist on classic American fare. Located atop Ponce City Market, it blends craft beers and elevated pub cuisine in a stylish indoor-outdoor destination.','https://blackhotelguide.com/wp-content/uploads/2020/01/3-color-268-png-vr-1.png'),
('Alma Cocina','Restaurant','191 Peachtree Street NE','Atlanta','GA','(404) 968-9662','https://www.alma-atlanta.com/','Located at 191 Peachtree Street NE, Alma Cocina offers a vibrant Latin‑inspired menu in a chic downtown setting. Since opening in 2011, the restaurant has earned acclaim for its creative dishes—from shellfish ceviche to masa‑fried shrimp tacos—and top‑tier margaritas, including one of Atlanta’s best. It’s the perfect spot for brunch, lunch, dinner, happy hour, or private events, with something delicious and thoughtfully crafted on every plate.','https://blackhotelguide.com/wp-content/uploads/2020/01/3-color-268-png-vr-1.png'),
('Fogo de Chão Brazilian Steakhouse','Restaurant','3101 Piedmont Rd','Atlanta','GA','(404) 266-9988','https://fogodechao.com/location/atlanta/','Located in Buckhead’s Piedmont Road dining district, Fogo de Chão is an upscale Brazilian churrascaria renowned for its tableside service of fire-roasted meats and expansive Market Table. A go-to for special occasions and corporate dinners, it blends vibrant Brazilian flavors with polished southern hospitality, offering a sophisticated setting for steak-lovers and celebrations alike.','https://blackhotelguide.com/wp-content/uploads/2025/06/Fogo-de-Chao-Brazilian-Steakhouse.jpg')
)
INSERT INTO public.businesses (name, business_name, category, address, city, state, phone, website, description, banner_url, owner_id, listing_status, is_verified)
SELECT s.business_name, s.business_name, s.category, NULLIF(s.address,''), NULLIF(s.city,''), NULLIF(s.state,''), NULLIF(s.phone,''), NULLIF(s.website,''), NULLIF(s.description,''), NULLIF(s.banner_url,''), 'bd72a75e-1310-4f40-9c74-380443b09d9b'::uuid, 'live', true
FROM src s
WHERE NOT EXISTS (SELECT 1 FROM public.businesses b WHERE lower(regexp_replace(b.business_name,'[^A-Za-z0-9]+','','g')) = lower(regexp_replace(s.business_name,'[^A-Za-z0-9]+','','g')));