WITH src(business_name,category,address,city,state,phone,website,description,banner_url) AS (VALUES
('Residence Inn by Marriott Louisville Downtown','Hotel','333 E Market St','Louisville','KY','','https://expedia.com/affiliates/louisville-hotels-residence-inn-by-marriott-louisville-downtown.ee1vIsk','Located in the vibrant downtown district, Residence Inn Louisville Downtown offers the perfect blend of extended-stay convenience and modern amenities. Ideal for business travelers, families, and guests looking for a home-like stay near Louisville’s top attractions.','https://blackhotelguide.com/wp-content/uploads/2020/01/3-color-268-png-vr-1.png'),
('Hampton Inn & Suites Boston Crosstown Center','Hotel','811 Massachusetts Avenue','Boston','MA','','https://expedia.com/affiliates/boston-hotels-hampton-inn-suites-boston-crosstown-center.JKRwEFy','This Black-owned hotel in Downtown Boston offers a welcoming and affordable stay with easy access to the city’s best attractions. Whether you’re traveling for business, leisure, or medical purposes, this well-appointed hotel provides the perfect blend of comfort and convenience.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2024/12/guest-room.jpg?fit=1200%2C800&ssl=1'),
('Alta Adams, Restaurant','Restaurant','5359 W Adams Blvd','Los Angeles','CA','','https://altaadams.com/','Helmed by two-time James Beard Award-nominated chef and co-owner Keith Corbin, Alta Adams is a vibrant Black-owned culinary destination redefining California soul food.','https://blackhotelguide.com/wp-content/uploads/2020/01/3-color-268-png-vr-1.png'),
('Homewood Suites by Hilton Lynnwood Seattle','Hotel','206 Western Ave W','Seattle','WA','206-xxx-xxxx','https://expedia.com/affiliates/seattle-hotels-homewood-suites-by-hilton-lynnwood-seattle-everett.DkTdoeV','This black-owned hotel is located in the heart of Seattle, offering a perfect balance of comfort, convenience, and extended-stay amenities. With spacious accommodations, complimentary breakfast, and modern conveniences, it makes for an ideal retreat. The hotel features all-suite rooms equipped with full kitchens, 24-hour fitness center, indoor pool, and business amenities.','https://blackhotelguide.com/wp-content/uploads/2020/01/3-color-268-png-vr-1.png'),
('MIDA, Italian Restaurant','Restaurant','782 Tremont Street','Boston','MA','(617) 936-3490','https://midarestaurant.com/','MIDA, founded by award-winning chef and owner Douglass Williams, offers an elevated yet approachable dining experience rooted in Italian-inspired cuisine. The restaurant features handmade pastas, seasonal dishes, and an exceptional beverage program, all in a stylish yet welcoming atmosphere.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2024/12/lobster-scampi.jpg?fit=1000%2C1250&ssl=1'),
('Ye Olde Manor House Bed & Breakfast','Bed & Breakfast','N7622 US-12','Elkhorn','WI','','https://www.yeoldemanorhouse.com/','A tranquil Black-owned country retreat with timeless charm and modern comforts. Nestled in the scenic countryside of southeastern Wisconsin, Ye Olde Manor House Bed & Breakfast is a Black-owned getaway offering refined comfort, gracious hospitality, and a serene escape from city life. This elegant English-style manor features beautifully appointed guest rooms, inviting common areas, and peaceful gardens that invite relaxation. Whether you’re planning a romantic weekend, a solo wellness retreat, or a private event, Ye Olde Manor House blends historic ambiance with contemporary amenities—all thoughtfully curated by warm and welcoming innkeepers.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/06/Ye-Olde-Manor-House-Bed-Breakfast-1.jpg?fit=1000%2C662&ssl=1'),
('Marriott San Francisco Union Square','Hotel','480 Sutter Street','San Francisco','CA','','https://expedia.com/affiliates/san-francisco-hotels-san-francisco-marriott-union-square.7psbF4n','Experience the vibrancy of San Francisco with a stay at the black-owned hotel in San Francisco CA Marriott San Francisco Union Square—a sophisticated retreat just steps away from the city’s best shopping, dining, and entertainment. Located in the iconic Union Square district, this upscale hotel provides the perfect blend of comfort, style, and convenience.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/02/exterior-24.jpg?fit=1024%2C683&ssl=1'),
('DoubleTree by Hilton New York Downtown','Hotel','8 Stone St','New York','NY','','https://expedia.com/affiliates/new-york-hotels-doubletree-by-hilton-new-york-downtown.LDxGd3p','Nestled in the heart of Lower Manhattan, DoubleTree by Hilton New York Downtown offers sleek city style and unbeatable convenience, just steps from Wall Street, Battery Park, and the Staten Island Ferry. Operated by Pyramid Global Hospitality, this hotel pairs business-class service with an authentic New York City experience.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/05/DoubleTree-by-Hilton-New-York-Downtown-NYC-7.jpg?fit=1024%2C683&ssl=1'),
('Narobia’s Grits & Gravy','Restaurant','2019 Habersham St','Savannah','GA','(912) 231-0563','https://narobias-grits-gravy.restaurants-world.com/','A beloved Black-owned eatery in Savannah, Georgia, Narobia’s Grits & Gravy has been serving up authentic Lowcountry breakfast and brunch delights for years. Known for its warm hospitality and mouthwatering dishes, this cozy spot has become a must-visit for both locals and tourists seeking a genuine taste of Southern comfort food.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/05/Narobias-Grits-Gravy-1.jpg?fit=1000%2C1000&ssl=1'),
('Ekiben Baltimore','Restaurant','1622 Eastern Ave','Baltimore','MD','','https://ekibenbaltimore.com/','Ekiben is a proudly Black- and Asian-owned fast-casual restaurant that has taken Baltimore by storm, known for its wildly popular steamed buns, rice bowls, and unforgettable tempura broccoli.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/08/Ekiben-6.jpg?fit=750%2C1000&ssl=1'),
('Ben’s Chili Bowl','Restaurant','1001 H St NE','Washington','DC','(202) 733-1895','https://benschilibowl.com/','A Spicy Slice of D.C. History, Black-Owned and Legendary. Since opening its doors in 1958 on the historic U Street Corridor, Ben’s Chili Bowl has become a Washington, D.C. icon—beloved by locals, celebrities, and travelers alike. Founded by Ben Ali, a Trinidadian immigrant of Indian descent, and his wife Virginia Ali, who is African American with Native American heritage, Ben’s has stayed true to its roots as a welcoming, family-run business. Today, the Ali family continues this legacy, serving up the legendary half-smokes, chili dogs, and classic diner fare that have made Ben’s a cultural landmark for generations.','https://blackhotelguide.com/wp-content/uploads/2025/07/Bens-Chili-Bowl-street-view-2.jpg'),
('Cane, Washington, D.C.','Restaurant','','Washington','D.C.','(202) 675-2011','https://www.cane-dc.com/','Opened in 2019 by Trinidadian-born siblings Chef Peter Prime and Jeanine Prime, Cane has quickly become a standout in Washington, D.C.’s dynamic dining scene. This Black-owned gem celebrates the rich, multicultural flavors of Trinidad and Tobago—blending African, Indian, Creole, and global influences into unforgettable dishes. Recognized with a Michelin Bib Gourmand, Cane offers an experience that’s both approachable and refined, making it a must-visit for locals and visitors alike.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/07/Cane-Washington-D.C.-1.jpg?fit=750%2C1000&ssl=1'),
('Elmina, Restaurant, Washington D.C.','Restaurant','2208 14th St NW','Washington','DC','','https://www.elminarestaurant.com/','Elmina is a black-owned restaurant in Washington D.C., the latest venture by acclaimed Ghanaian-American chef Eric Adjepong, bringing the rich, vibrant flavors of West Africa to the area. Named after the historic coastal town in Ghana, Elmina celebrates African culinary heritage with modern twists, offering a menu inspired by traditional West African cuisine. Guests can enjoy signature dishes, handcrafted cocktails, and warm, chic interiors, all sourced from locally and ethically inspired ingredients.','https://blackhotelguide.com/wp-content/uploads/2020/01/3-color-268-png-vr-1.png'),
('Colada Shop','Restaurant','7993 Tuckerman Lane','Potomac','MD','(240) 332-8870','https://www.coladashop.com/','Vibrant Cuban Café & Bar, Latino-Owned and Full of Flavor in VA. Colada Shop brings the energy and charm of Cuban café culture to the heart of Washington, D.C., offering authentic Cuban-inspired bites and signature coffee drinks.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/07/Colada-Shop-Maryland-4.jpg?fit=750%2C1000&ssl=1'),
('Residence Inn Baltimore at The Johns Hopkins Medical Campus','Hotel','800 N Wolfe St','Baltimore','MD','(443) 524-8400','https://expedia.com/affiliates/baltimore-hotels-residence-inn-by-marriott-baltimore-at-the-johns-hopkins-medical-campus.IqMbcCr','Experience comfort, convenience, and thoughtful amenities at the black-owned hotel Residence Inn Baltimore at The Johns Hopkins Medical Campus. This extended-stay hotel is perfect for patients, visiting families, medical professionals, and business travelers alike.','https://blackhotelguide.com/wp-content/uploads/2020/01/3-color-268-png-vr-1.png'),
('Magdalena, A Maryland Bistro, at Ivy Hotel','Restaurant','205 E Biddle St','Baltimore','MD','(410) 514-0303','https://www.theivybaltimore.com/dine/magdalena','Nestled within the historic, Black-owned Ivy Hotel, Magdalena restaurant offers an elegant yet approachable dining experience that celebrates seasonal Maryland ingredients with European technique and creativity.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/08/Magdalena-A-Maryland-Bistro-1.jpg?fit=991%2C1000&ssl=1'),
('Jerk at Nite','Restaurant','21 N Eutaw St','Baltimore','MD','','https://jerkatnite.com/','Jerk at Nite is a proudly Black-owned Caribbean fusion restaurant that has become a local legend for its mouthwatering jerk chicken, island-inspired plates, and late-night energy. Celebrated for its creative take on Jamaican classics, Jerk at Nite brings the heat, heart, and hospitality of the Caribbean to the DMV’s vibrant dining scene.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/08/Jerk-At-Nite-3.jpg?fit=750%2C1000&ssl=1'),
('Papi Cuisine','Restaurant','2 E Wells St #116','Baltimore','MD','','https://www.papicuisine.com/','Papi Cuisine is a Black-owned culinary hotspot in Baltimore, known for its bold take on Afro-Latin fusion cuisine. This upscale yet welcoming restaurant blends rich flavors, artistic presentation, and a lively atmosphere, making it a must-visit for food lovers seeking a unique dining experience. From its famous lobster, crab, and shrimp stuffed seafood egg rolls to perfectly seasoned lamb chops, every dish at Papi Cuisine is crafted with precision and passion. Whether you’re dining in for an intimate meal or celebrating a special occasion, this standout eatery delivers unforgettable flavors with a side of luxury.','https://blackhotelguide.com/wp-content/uploads/2020/01/3-color-268-png-vr-1.png'),
('Sheraton Los Angeles San Gabriel','Hotel','303 E Valley Blvd','San Gabriel','CA','N/A','https://expedia.com/affiliates/los-angeles-hotels-sheraton-los-angeles-san-gabriel.r7bb90L','Blending modern elegance with Asian-inspired hospitality, this black-owned hotel in Los Angeles, California offers a sophisticated retreat in the San Gabriel Valley. Guests will enjoy luxurious accommodations, world-class dining, and access to cultural attractions.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/01/fitness-center-32.jpg?fit=1200%2C800&ssl=1'),
('Rooted Rotisserie','Restaurant','1116 Hollins St','Baltimore','MD','','https://www.rootedrotisserie.com/','Flavor-Focused Rotisserie with Deep Roots in Black Ownership & Baltimore Community. Known for juicy, herb-marinated chicken, creative sides, and scratch-made sauces. Located in Baltimore, Maryland, with a neighborhood-friendly, casual vibe. Catering services for family gatherings, office events, and special occasions.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/08/Rooted-Rotisserie-1.jpg?fit=750%2C1000&ssl=1')
)
INSERT INTO public.businesses (name, business_name, category, address, city, state, phone, website, description, banner_url, owner_id, listing_status, is_verified)
SELECT s.business_name, s.business_name, s.category, NULLIF(s.address,''), NULLIF(s.city,''), NULLIF(s.state,''), NULLIF(s.phone,''), NULLIF(s.website,''), NULLIF(s.description,''), NULLIF(s.banner_url,''), 'bd72a75e-1310-4f40-9c74-380443b09d9b'::uuid, 'live', true
FROM src s
WHERE NOT EXISTS (SELECT 1 FROM public.businesses b WHERE lower(regexp_replace(b.business_name,'[^A-Za-z0-9]+','','g')) = lower(regexp_replace(s.business_name,'[^A-Za-z0-9]+','','g')));