WITH src(business_name,category,address,city,state,phone,website,description,banner_url) AS (VALUES
('Mojave','Restaurant','6450 Powers Ferry Rd NW','Sandy Springs','GA','(678) 927-2332','https://mojaverestaurant.com/','Latin-inspired flavors with a view in Sandy Springs, this Latin American restaurant offers a soulful mix of classic and contemporary dishes, featuring handcrafted cocktails and a vibrant ambiance.','https://blackhotelguide.com/wp-content/uploads/2020/01/3-color-268-png-vr-1.png'),
('Hippin Hops Brewpub & Oyster Bar','Brewpub','1308 Glenwood Ave SE','Atlanta','GA','(678) 713-2739','https://www.hippinhopsbrewery.com/','As Georgia’s first Black-owned brick-and-mortar brewery, Hippin Hops Brewpub & Oyster Bar is breaking boundaries and pouring flavor. Blending Southern charm with coastal cuisine and craft brews, it offers an atmosphere that’s bold and refreshing.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/06/Hippin-Hops-Brewpub-Oyster-Bar.jpg?fit=1000%2C750&ssl=1'),
('Hippin’ Hops Brewery','Brewery','1308 Glenwood Ave SE','Atlanta','GA','678.713.2739','https://www.hippinhopsbrewery.com/','Hippin’ Hops Brewery has made history as Atlanta’s first Black-owned brewery with a standalone taproom, offering a vibrant fusion of quality brewing, elevated pub fare, and unapologetic Southern charm.','https://blackhotelguide.com/wp-content/uploads/2020/01/3-color-268-png-vr-1.png'),
('Service Bar, Washington, D.C.','Lodging','926-928 U St NW','Washington','DC','(202) 462-7232','https://www.servicebardc.com/','Craft Cocktails, Community Vibes. Located in the vibrant U Street Corridor, Service Bar DC is a Black-owned cocktail haven known for its inventive drinks and cozy atmosphere.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/05/Service-Bar-Washington-D.C.-3.jpg?fit=1000%2C750&ssl=1'),
('Paschal’s Restaurant & Bar','Restaurant','180 Northside Dr SW','Atlanta','GA','(404) 835-0833','https://paschals.restaurant/','An Atlanta soul food landmark with a Civil Rights legacy and modern Southern flair, serving signature Southern cuisine in a stylish setting near downtown Atlanta.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/06/Paschals-Restaurant-Bar-7.jpg?fit=1000%2C1333&ssl=1'),
('The Silver Room','Lodging','1506 E 53rd St','Chicago','IL','','','Located in the heart of Hyde Park, Chicago, The Silver Room is more than just a retail space—it’s a vibrant cultural hub celebrating art, music, and community. Founded in 1997 by Eric Williams, this Black-owned book & gift shop in Chicago offers a curated selection of handcrafted jewelry, fashion, accessories, and home décor, while also serving as a gathering place for creatives, entrepreneurs, and activists.','https://blackhotelguide.com/wp-content/uploads/2025/03/The-Silver-Room-4-.jpg'),
('Thee Matriarch Bed & Breakfast','B&B','1170 Fischer St.','Orangeburg','SC','(803) 937-4271','https://www.facebook.com/TheeMatriarch/','Tucked in the heart of downtown Orangeburg, South Carolina, Thee Matriarch Bed & Breakfast is a vibrant, family-owned retreat that blends historic elegance with contemporary comfort—and a whole lot of soul. Known for its warm hospitality, decadent Southern breakfasts, and spirited community engagement, this B&B offers a personalized lodging experience for romantic getaways, special celebrations, and business travelers.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/07/Thee-Matriarch-Bed-Breakfast-SC-3.jpg?fit=1000%2C667&ssl=1'),
('HYATT house Cypress/Anaheim','Hotel','5905 Corporate Avenue','Cypress','CA','','https://expedia.com/affiliates/cypress-hotels-hyatt-house-cypressanaheim.KA3xoTG','This black-owned hotel in Cypress, Orange County California is located just minutes from Disneyland, Knott’s Berry Farm, and major business hubs, the HYATT house Cypress/Anaheim is the perfect home away from home for business travelers, families, and extended stays. Offering spacious suites with full kitchens, complimentary breakfast, and a welcoming atmosphere.','https://blackhotelguide.com/wp-content/uploads/2020/01/3-color-268-png-vr-1.png'),
('Dooky Chase’s Restaurant','Restaurant','2301 Orleans Avenue','New Orleans','LA','(504) 821-0600','http://www.dookychaserestaurant.com','A legendary culinary institution in New Orleans, symbolizing tradition and culture with specialties in Creole cuisine, and a key historic landmark during the Civil Rights Movement.','https://blackhotelguide.com/wp-content/uploads/2020/01/3-color-268-png-vr-1.png'),
('Neyow’s Creole Café','Restaurant','3332 Bienville St','New Orleans','LA','(504) 827-5474','https://neworleans.neyows.com/new-orleans-neyow-s-creole-cafe-new-orleans-food-menu','Neyow’s Creole Café offers an immersive experience into the heart of New Orleans’ culinary heritage, featuring authentic Creole cuisine and a family-friendly dining environment.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/05/Neyows-creole-cafe-3.jpg?fit=1000%2C750&ssl=1'),
('DoubleTree by Hilton Hotel New Orleans Airport','Hotel','2150 Veterans Memorial Blvd','Kenner','LA','','https://expedia.com/affiliates/new-orleans-hotels-doubletree-by-hilton-hotel-new-orleans-airport.d4vb5vy','This black-owned hotel in New Orleans is conveniently located near Louis Armstrong New Orleans International Airport, offering a blend of modern comfort and warm hospitality, perfect for business and leisure travelers. Known for its signature chocolate chip cookie welcome, this hotel ensures a relaxing and seamless stay just minutes from the vibrant culture of downtown New Orleans.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/01/hotel-pool-view.jpg?fit=1024%2C683&ssl=1'),
('La Posada Inn & Felix’s Cantina','Boutique Inn','210 2nd Street','Milford','PA','','https://expedia.com/affiliates/milford-hotels-la-posada.J9EUVQ7','A Latino-owned boutique getaway in Milford, Pennsylvania, bringing the colors, flavors, and hospitality of Mexico’s Yucatán Peninsula to the heart of the Poconos. Family-run and community-driven, with cozy accommodations and an immersive cultural experience.','https://blackhotelguide.com/wp-content/uploads/2020/01/3-color-268-png-vr-1.png'),
('We Dat’s, NORLA','Restaurant','1407 Canal St., New Orleans, LA 70112','New Orleans','LA','(504) 252-4920','http://www.wedatschickenandshrimp.com','We Dat’s has become a local favorite and a vibrant part of New Orleans’ food scene, offering flavorful dishes with bold seasoning and Southern charm. Known for their signature fried chicken wings and jumbo shrimp, it’s a quintessential New Orleans experience.','https://blackhotelguide.com/wp-content/uploads/2020/01/3-color-268-png-vr-1.png'),
('Morrow Steak','Restaurant','1003 Julia St','New Orleans','LA','(504) 354-9805','https://www.morrowsteak.com/','Morrow Steak is a Black-owned fine dining steakhouse located in New Orleans’ Warehouse District. It offers a menu featuring premium steaks, fresh seafood, and a full-service bar in an elegant atmosphere.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/05/Morrow-Steak-New-Orleans-8.jpg?fit=750%2C1000&ssl=1'),
('ChòpnBlọk','Restaurant','401 Franklin St Suite A','Houston','TX','(281) 631-5009','https://chopnblok.co/','In the heart of Houston’s Montrose neighborhood, ChòpnBlọk stands as a vibrant testament to West African culinary heritage, reimagined through the lens of Nigerian-American entrepreneur and chef Ope Amosu.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/05/ChopnBlok-Houston-Texas-4.jpg?fit=750%2C1000&ssl=1'),
('Residence Inn Austin The Domain Area','Hotel','11301 Burnet Rd','Austin','TX','','https://expedia.com/affiliates/austin-hotels-residence-inn-by-marriott-austin-the-domain-area.nkag4z7','Comfort Meets Culture Near Austin’s Trendiest District. Located in Austin’s bustling Domain area, this Residence Inn offers extended-stay convenience with modern, welcoming style, ideal for visitors seeking both comfort and cultural exploration. It features spacious suites with full kitchens, complimentary breakfast, fitness center, and is pet-friendly.','https://blackhotelguide.com/wp-content/uploads/2020/01/3-color-268-png-vr-1.png'),
('Do Not Disturb, Speakeasy, Manhattan, NYC','Speakeasy','285 W 12th St','New York','NY','Not provided','https://www.dnd-nyc.com/','A hidden speakeasy offering an intimate, candle-lit escape with vintage elegance and craft mixology. Ideal for lovers, friends, or anyone in search of memorable cocktails.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/11/Do-Not-Disturb-Speakeasy-Manhattan-NYC.jpg?fit=750%2C1000&ssl=1'),
('Pur Noire Urban Wineries','Winery','802 Milam Street','Houston','TX','','https://www.purnoirewines.com/','Pur Noire Urban Wineries is redefining wine culture in America as Houston’s first Black-owned winery and tasting room. Founded by husband-and-wife entrepreneurs Kenneth and Denisse Stephens, Pur Noire brings the richness of Napa Valley wines to an elegant urban space in downtown Houston. Known for its award-winning, limited-production varietals and luxury tasting experiences, this boutique winery offers guests a sophisticated escape rooted in Black excellence, culture, and craftsmanship.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/10/Pur-Noire-Urban-Wineries-%E2%80%93-Houston-Texas.jpg?fit=750%2C1000&ssl=1'),
('Embassy Suites by Hilton Dallas Love Field','Hotel','3880 W Northwest Hwy','Dallas','TX','','https://expedia.com/affiliates/dallas-hotels-embassy-suites-dallas-lovefield.LOYuA59','Conveniently located near Dallas Love Field Airport, this Black-owned hotel offers a relaxing retreat with all-suite accommodations and modern amenities. Ideal for business travelers and families, it provides easy access to downtown and popular attractions. Guests enjoy complimentary breakfast, evening receptions, and stunning views of Bachman Lake.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/02/pool-41.jpg?fit=1024%2C691&ssl=1'),
('Embassy Suites Minneapolis Airport','Hotel','7901 34th Ave S','Bloomington','MN','','https://expedia.com/affiliates/minneapolis-st-paul-hotels-embassy-suites-by-hilton-minneapolis-airport.O4JRdx1','Located just minutes from Minneapolis-St. Paul International Airport, Embassy Suites Minneapolis Airport offers a stylish and comfortable stay with all-suite accommodations and premium amenities. This Black-owned hotel in Minneapolis, Minnesota is ideal for business travelers, families, and visitors looking for easy access to Mall of America, downtown Minneapolis, and top attractions in the Twin Cities. With complimentary breakfast and a nightly reception, guests can enjoy a seamless blend of convenience and hospitality.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/02/dining-49.jpg?fit=765%2C1020&ssl=1')
)
INSERT INTO public.businesses (name, business_name, category, address, city, state, phone, website, description, banner_url, owner_id, listing_status, is_verified)
SELECT s.business_name, s.business_name, s.category, NULLIF(s.address,''), NULLIF(s.city,''), NULLIF(s.state,''), NULLIF(s.phone,''), NULLIF(s.website,''), NULLIF(s.description,''), NULLIF(s.banner_url,''), 'bd72a75e-1310-4f40-9c74-380443b09d9b'::uuid, 'live', true
FROM src s
WHERE NOT EXISTS (SELECT 1 FROM public.businesses b WHERE lower(regexp_replace(b.business_name,'[^A-Za-z0-9]+','','g')) = lower(regexp_replace(s.business_name,'[^A-Za-z0-9]+','','g')));