WITH src(business_name,category,address,city,state,phone,website,description,banner_url) AS (VALUES
('Embassy Suites by Hilton Boston Marlborough','Hotel','123 Boston Post Road West','Marlborough','Massachusetts','','https://expedia.com/affiliates/worcester-hotels-embassy-suites-by-hilton-boston-marlborough.f2ZP2Yx','Located in the heart of Central Massachusetts’ MetroWest region, Embassy Suites by Hilton Boston Marlborough offers spacious all-suite accommodations, complimentary breakfast, and thoughtful amenities ideal for business, family, and leisure travelers.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2026/02/Embassy-Suites-by-Hilton-Boston-Marlborough-Guestroom-%E2%80%94-Marlborough-Massachusetts.jpg?fit=1024%2C683&ssl=1'),
('Hilton Garden Inn Los Angeles / Hollywood','Hotel','2005 North Highland Avenue','Los Angeles','CA','','https://expedia.com/affiliates/los-angeles-hotels-hilton-garden-inn-los-angeleshollywood.mW2Jspn','Located in the heart of Tinsel town, this black-owned hotel in Los Angeles Hollywood area places guests within walking distance of iconic Hollywood landmarks, offering the perfect blend of comfort, convenience, and style.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/01/pool-area.jpg?fit=1024%2C683&ssl=1'),
('Middle Eight — Covent Garden','Boutique Hotel','66 Great Queen St','London','WC2B 5BX','','https://expedia.com/affiliates/london-hotels-middle-eight-covent-garden-preferred-hotels-and-resorts.XgZjOqB','Middle Eight Covent Garden is a polished boutique hotel that blends understated luxury with a distinctly musical soul. It features elegant guest rooms and suites, a live-music–inspired ambiance, on-site restaurant, and easy access to cultural experiences in London.','https://blackhotelguide.com/wp-content/uploads/2026/02/Middle-Eight-%E2%80%94-Covent-Garden-London-United-Kingdom.jpg'),
('Residence Inn by Marriott London Tower Bridge','Hotel','190 Bermondsey Street','London','SE1 3TQ','','https://expedia.com/affiliates/london-hotels-residence-inn-by-marriott-london-tower-bridge.7hpsvow','The Residence Inn by Marriott London Tower Bridge is a 4-star, all-suite hotel located in the Southwark district, designed for both short and extended stays. It blends modern living with historic surroundings, managed under Black executive leadership.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2026/02/Residence-Inn-by-Marriott-London-Tower-Bridge-amenities.jpg?fit=512%2C768&ssl=1'),
('Radisson Blu Hotel, London Leicester Square','Hotel','31–36 Leicester Square','London','WC2H','','https://expedia.com/affiliates/london-hotels-radisson-blu-hampshire-hotel.t4FIzdg','In the heart of London’s entertainment district, Radisson Blu Leicester Square offers a front-row seat to the West End. Managed by Pyramid Global Hospitality under Black executive leadership, the hotel pairs location with upscale service.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2026/02/Radisson-Blu-Hotel-London-Leicester-Square.jpg?fit=1024%2C683&ssl=1'),
('Hilton Garden Inn San Antonio Downtown Riverwalk','Hotel','408 E Houston Street','San Antonio','Texas','','https://expedia.com/affiliates/san-antonio-hotels-hilton-garden-inn-san-antonio-downtown.efpFBZk','Set just steps from San Antonio’s iconic River Walk, Hilton Garden Inn San Antonio Downtown Riverwalk offers modern comfort in the heart of one of Texas’s most culturally rich cities.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2026/02/Hilton-Garden-Inn-San-Antonio-Downtown-Riverwalk-%E2%80%94-San-Antonio-Texas-guestroom-2.jpg?fit=1024%2C683&ssl=1'),
('Cambria Hotel Pittsburgh – Downtown','Hotel','1320 Centre Avenue','Pittsburgh','Pennsylvania','','https://expedia.com/affiliates/pittsburgh-hotels-cambria-hotel-pittsburgh-downtown.VSmkQMe','Located in Pittsburgh’s vibrant Uptown district near PPG Paints Arena, Cambria Hotel Pittsburgh – Downtown offers contemporary comfort in one of the city’s most energetic corridors. Designed for both business and leisure travelers, the hotel provides spacious accommodations, upscale amenities, and easy access to downtown attractions.','https://blackhotelguide.com/wp-content/uploads/2026/02/Cambria-Hotel-Pittsburgh-Downtown-%E2%80%94-Pittsburgh-Pennsylvania.jpg'),
('Hilton Garden Inn Seattle Downtown','Hotel','1821 Boren Ave','Seattle','Washington','','https://expedia.com/affiliates/seattle-hotels-hilton-garden-inn-seattle-downtown.866O3FD','Located in the heart of downtown Seattle, Hilton Garden Inn Seattle Downtown offers contemporary accommodations just steps from the city’s most iconic attractions. Whether visiting for business, cruise departures, or a Pacific Northwest getaway, guests enjoy the reliability of the Hilton brand paired with central-city convenience.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2026/02/Hilton-Garden-Inn-Seattle-Downtown-%E2%80%94-Seattle-Washington-USA.jpg?fit=1024%2C683&ssl=1'),
('Hotel Indigo Cleveland Downtown','Hotel','651 Huron Road E','Cleveland','Ohio','','https://expedia.com/affiliates/cleveland-hotels-hotel-indigo-cleveland-downtown.Ve8BKrx','Located in Cleveland’s vibrant Gateway District, Hotel Indigo Cleveland Downtown offers a boutique, neighborhood-driven experience just steps from the city’s major sports, entertainment, and cultural venues. The hotel is professionally managed by Pyramid Global Hospitality, making it a Black-managed hotel under Black executive leadership.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2026/02/Hotel-Indigo-Cleveland-Downtown-%E2%80%94-Cleveland-Ohio-guestroom.jpg?fit=1024%2C683&ssl=1'),
('The Sweet House – Dreamy Home in East Nashville','Vacation Rental','3119A Brickdale Lane','Nashville','TN','','https://expedia.com/affiliates/nashville-hotels-the-sweet-house-dreamy-home-in-east-nashville.nKRCumZ','A chic, Black-owned vacation rental offering a mix of comfort, style, and convenience in the heart of Nashville.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/05/The-Sweet-House-Dreamy-Home-in-East-Nashville-3.jpg?fit=360%2C240&ssl=1'),
('Residence Inn Palo Alto Los Altos','Hotel','4460 El Camino Real','Los Altos','CA','','https://expedia.com/affiliates/los-altos-hotels-residence-inn-marriott-palo-alto-los-altos.eVAdjeT','The Residence Inn Palo Alto Los Altos offers a comfortable and convenient extended-stay experience in the heart of Silicon Valley, featuring spacious accommodations, thoughtful amenities, and easy access to top tech hubs.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/01/outdoor-pool-and-spa-1.jpg?fit=1200%2C800&ssl=1'),
('DoubleTree by Hilton Hotel Jacksonville Airport','Hotel','2101 Dixie Clipper Dr','Jacksonville','FL','','https://expedia.com/affiliates/jacksonville-hotels-doubletree-by-hilton-hotel-jacksonville-airport.4kd1Hsf','Effortless Comfort Steps from the Runway. Nestled just minutes from your gate, the DoubleTree by Hilton Hotel Jacksonville Airport offers a seamless blend of convenience, comfort, and Southern hospitality. This welcoming hotel exemplifies modern travel ease with a commitment to exceptional service and inclusion. Guests enjoy stylish guest rooms, onsite dining, an outdoor pool, and a fitness center, making it ideal for both business and leisure travelers.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/05/DoubleTree-Jacksonville-Airport-6.jpg?fit=1024%2C683&ssl=1'),
('Embassy Suites by Hilton Fort Myers Estero','Hotel','10450 Corkscrew Commons Dr','Estero','FL','N/A','https://expedia.com/affiliates/fort-myers-hotels-embassy-suites-by-hilton-fort-myers-estero.ea7HlZy','This black-owned hotel in Fort Myers Florida is located just minutes from Southwest Florida’s pristine beaches, offering a stylish and comfortable retreat for business and leisure travelers alike. This all-suite, Black-owned hotel provides a blend of convenience and luxury, with spacious accommodations, complimentary made-to-order breakfast, and easy access to top attractions like Gulf Coast Town Center and Lovers Key State Park.','https://blackhotelguide.com/wp-content/uploads/2020/01/3-color-268-png-vr-1.png'),
('The Westin Washington National Harbor','Hotel','171 Waterfront Street','National Harbor','MD','','https://expedia.com/affiliates/college-park-hotels-the-westin-washington-national-harbor.dK4xQ6R','Waterfront Luxury Near the Nation’s Capital. An upscale hotel offering stunning views, sophisticated accommodations, and thoughtful amenities designed for both relaxation and productivity.','https://blackhotelguide.com/wp-content/uploads/2020/01/3-color-268-png-vr-1.png'),
('DoubleTree Suites by Hilton Orlando – Disney Springs™ Area','Hotel','2305 Hotel Plaza Blvd','Lake Buena Vista','FL','','https://expedia.com/affiliates/orlando-hotels-doubletree-suites-by-hilton-orlando-disney-springs-area.xXFWWJ8','Experience a magical stay near the magic with spacious accommodations and family-friendly amenities just minutes from Walt Disney World® Resort. This black-owned hotel provides exclusive perks, including early theme park entry and complimentary shuttle service to the parks.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/01/doubletree-suites-by-1.jpg?fit=1200%2C797&ssl=1'),
('Los Félix Miami','Restaurant','3413 Main Hwy','Miami','FL','(786) 391-1598','https://www.losfelixmiami.com/','Modern Mexican Flavors Rooted in Heritage. A standout Latino‑owned hotspot in Coconut Grove, Los Félix is a Michelin‑recognized celebration of ancestral Mexican cuisine.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/06/Los-Felix-Miami-Restaurant.jpg?fit=1000%2C1333&ssl=1'),
('Hampton Inn & Suites','Hotel','1500 Opus Place','Downers Grove','Illinois','','https://expedia.com/affiliates/chicago-hotels-chicago-marriott-suites-downers-grove.f4cpCCZ','Black-Owned Full-Service Hotel with Community Roots and Warm Hospitality. Ideal for business travelers, family getaways, and guests exploring the greater Chicagoland area, this property combines trusted Hampton Inn comfort with the distinctive leadership and community engagement of its Black ownership.','https://blackhotelguide.com/wp-content/uploads/2020/01/3-color-268-png-vr-1.png'),
('Hampton Inn Nashville/Vanderbilt University','Hotel','1919 West End Ave','Nashville','TN','','https://expedia.com/affiliates/nashville-hotels-hampton-inn-nashvillevanderbilt.0Rq3KuO','Black-Owned Hotel with Central Location & Comfort-Driven Hospitality. Located just steps from one of Nashville’s most dynamic neighborhoods, offering comfortable, convenient stays. Among highlights, the hotel features complimentary breakfast, Wi-Fi, fitness center, and proximity to local attractions.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2026/02/Hampton-Inn-Nashville-Vanderbilt.jpg?fit=1024%2C683&ssl=1'),
('Homewood Suites by Hilton Largo Washington, D.C. Area','Hotel','9103 Basil Ct','Largo','MD','','https://expedia.com/affiliates/waldorf-hotels-homewood-suites-by-hilton-largowashington.iDApo3h','Black-Owned Extended-Stay Hotel with Warm Hospitality & Convenient Location. Homewood Suites by Hilton Largo Washington, D.C. Area is a Black-owned extended-stay property that blends comfort, convenience, and thoughtful service for travelers visiting the nation’s capital and surrounding suburbs. With spacious suites, complimentary amenities, and a welcoming atmosphere, this hotel is ideal for business travelers, families, and visitors planning longer stays.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2026/02/Homewood-Suites-by-Hilton-Largo-Washington-DC.jpg?fit=1024%2C683&ssl=1'),
('Jackson Soul Food, Miami','Restaurant','950 NW 3rd Ave','Miami','FL','(305) 374-7661','https://jackson-soul-food.restaurants-world.com/','Jackson Soul Food has been delighting Miami with soulful, home-cooked dishes since 1946, serving hearty classics like shrimp & grits, fried catfish, smothered pork chops, and collard greens in a warm and welcoming atmosphere.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/06/Jackson-Soul-Food-Miami-1.jpg?fit=750%2C1000&ssl=1')
)
INSERT INTO public.businesses (name, business_name, category, address, city, state, phone, website, description, banner_url, owner_id, listing_status, is_verified)
SELECT s.business_name, s.business_name, s.category, NULLIF(s.address,''), NULLIF(s.city,''), NULLIF(s.state,''), NULLIF(s.phone,''), NULLIF(s.website,''), NULLIF(s.description,''), NULLIF(s.banner_url,''), 'bd72a75e-1310-4f40-9c74-380443b09d9b'::uuid, 'live', true
FROM src s
WHERE NOT EXISTS (SELECT 1 FROM public.businesses b WHERE lower(regexp_replace(b.business_name,'[^A-Za-z0-9]+','','g')) = lower(regexp_replace(s.business_name,'[^A-Za-z0-9]+','','g')));