INSERT INTO businesses (business_name, name, description, category, address, city, state, zip_code, phone, email, website, is_verified, latitude, longitude, owner_id, banner_url)
VALUES 
(
  'Ray Ray''s Hog Pit',
  'Ray Ray''s Hog Pit',
  'A Central Ohio BBQ institution since 2009, Ray Ray''s Hog Pit combines old-school smoke with new-school magic across 5 locations. Famous for St. Louis-style ribs, brisket, smoked wings, and pulled pork served from their iconic food truck at Ace of Cups in Clintonville.',
  'Restaurant',
  '2619 N High St',
  'Columbus',
  'OH',
  '43202',
  '(614) 753-1191',
  'info@rayrayshogpit.com',
  'https://rayrayshogpit.com',
  true,
  40.0220,
  -83.0060,
  'bd72a75e-1310-4f40-9c74-380443b09d9b',
  '/images/businesses/ray-rays-hog-pit-columbus.jpg'
),
(
  'Zweli''s',
  'Zweli''s',
  'INDY Week''s 2021 Best Chef in Durham County, Chef Zweli Williams takes your palate on an international journey right in Durham, NC. Zweli''s offers elevated dining with global flavors, expanded catering, group cooking classes, and special events throughout the year.',
  'Restaurant',
  '318 Blackwell St',
  'Durham',
  'NC',
  '27701',
  '(919) 251-8501',
  'info@zwelis.com',
  'https://www.zwelis.com',
  true,
  35.9940,
  -78.9060,
  'bd72a75e-1310-4f40-9c74-380443b09d9b',
  '/images/businesses/zwelis-durham.jpg'
),
(
  'Mrs. Kitchen Soul Food Restaurant',
  'Mrs. Kitchen Soul Food Restaurant',
  'A beloved Black-owned soul food restaurant in San Antonio cooking with love because it makes the food taste better. Chef LA serves up oven-baked ribs, collard greens, mac and cheese, and other Southern classics that keep the community coming back. Open Tuesday through Sunday.',
  'Restaurant',
  '2242 E Commerce St',
  'San Antonio',
  'TX',
  '78203',
  '(210) 549-4392',
  'mrs.kitchen_soulfood@yahoo.com',
  'https://mrskitchensa.com',
  true,
  29.4230,
  -98.4760,
  'bd72a75e-1310-4f40-9c74-380443b09d9b',
  '/images/businesses/mrs-kitchen-san-antonio.jpg'
);