
INSERT INTO public.businesses (owner_id, business_name, name, category, city, state, website, description, listing_status, is_verified)
VALUES
  ('bd72a75e-1310-4f40-9c74-380443b09d9b','Aspen Meadows Resort','Aspen Meadows Resort','Resort','Aspen','CO','https://www.aspenmeadows.com','Black-owned (Salamander Collection) Bauhaus-inspired resort in Aspen, Colorado.','live',true),
  ('bd72a75e-1310-4f40-9c74-380443b09d9b','Innisbrook Resort','Innisbrook Resort','Resort','Palm Harbor','FL','https://www.innisbrookgolfresort.com','Black-owned (Salamander Collection) golf resort home to the PGA TOUR Valspar Championship.','live',true),
  ('bd72a75e-1310-4f40-9c74-380443b09d9b','PGA National Resort & Spa','PGA National Resort & Spa','Resort','Palm Beach Gardens','FL','https://www.pgaresort.com','Premier Black-owned (Salamander Collection) golf and wellness destination in Florida.','live',true),
  ('bd72a75e-1310-4f40-9c74-380443b09d9b','The Mansion at Noble Lane','The Mansion at Noble Lane','Luxury Boutique Hotel','Bethany','PA','https://www.themansionatnoblelane.com','Black-owned luxury boutique resort and spa on a Gilded Age estate in the Pocono Mountains.','live',true),
  ('bd72a75e-1310-4f40-9c74-380443b09d9b','The Pierside Santa Monica','The Pierside Santa Monica','Boutique Hotel','Santa Monica','CA','https://www.piersidesantamonica.com','Black-owned premium lifestyle hotel steps from the Santa Monica Pier.','live',true),
  ('bd72a75e-1310-4f40-9c74-380443b09d9b','Hotel Tonnelle New Orleans','Hotel Tonnelle New Orleans','Boutique Hotel','New Orleans','LA','https://www.hoteltonnelle.com','Black-owned boutique hotel on St. Charles Avenue, part of Marriott Tribute Portfolio.','live',true),
  ('bd72a75e-1310-4f40-9c74-380443b09d9b','Chateau LeMoyne French Quarter','Chateau LeMoyne French Quarter','Hotel','New Orleans','LA','https://www.chateaulemoyne.com','Historic Black-owned hotel in the heart of the French Quarter.','live',true),
  ('bd72a75e-1310-4f40-9c74-380443b09d9b','The Oak Bluffs Inn','The Oak Bluffs Inn','Bed and Breakfast','Oak Bluffs','MA','https://www.oakbluffsinn.com','4-star Black-owned Victorian bed and breakfast on Martha''s Vineyard.','live',true),
  ('bd72a75e-1310-4f40-9c74-380443b09d9b','Morgan and Wells Bed & Breakfast','Morgan and Wells Bed & Breakfast','Bed and Breakfast','Shelby','NC','https://www.morganandwells.com','Black-owned Craftsman-style bed and breakfast in Shelby, North Carolina.','live',true),
  ('bd72a75e-1310-4f40-9c74-380443b09d9b','Center Lovell Inn','Center Lovell Inn','Bed and Breakfast','Lovell','ME','https://www.centerlovellinn.com','Charming Black-owned inn nestled in the picturesque town of Lovell, Maine.','live',true),
  ('bd72a75e-1310-4f40-9c74-380443b09d9b','Aurora Anguilla Resort & Golf Club','Aurora Anguilla Resort & Golf Club','Luxury Resort','Anguilla','AI','https://www.auroraanguilla.com','Black-owned (Salamander Collection) ultra-luxury 5-star resort on Rendezvous Bay, Anguilla.','live',true);
