WITH src(business_name,category,address,city,state,phone,website,description,banner_url) AS (VALUES
('La Jamaca Hotel & Restaurant','Hotel','Reparto Laborde','La Parguera','Lajas','','https://expedia.com/affiliates/lajas-hotels-la-jamaca.nDNae34','An eco-certified gem in La Parguera, Lajas, proudly Puerto Rican-owned and family-operated. It focuses on sustainability and local cuisine with personalized service.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/06/La-Jamaca-Hotel-Restaurant-Puerto-Rico-full-bar.jpg?fit=576%2C768&ssl=1'),
('Lazy Parrot Inn','Boutique Inn','Carr. 413 Km 4.1','Rincon','Puerto Rico','','https://expedia.com/affiliates/hotel-search-lazy-parrot-inn.15Onlmm','Tucked into the lush hills of Rincón’s west coast, the Lazy Parrot Inn is a proudly Puerto Rican-owned boutique inn that blends laid-back island vibes with warm Boricua hospitality. Known for its vibrant tropical ambiance, locally inspired food, and proximity to some of Puerto Rico’s best surf and sunset spots.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/12/Lazy-Parrot-Inn.jpg?fit=1024%2C683&ssl=1'),
('Mercato della Pescheria','Restaurant','412 Española Way','Miami Beach','FL','(305) 534-5822','https://www.mercatodellapescheria.com/miami-locations/','Authentic Italian Seafood Market Meets Miami Beach Culture. It blends fresh seafood, cured meats, house-made pasta, and artisanal cocktails in a lively, family-friendly atmosphere.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/06/mercato-della-pescheria.jpg?fit=1000%2C1333&ssl=1'),
('Quality Inn & Suites Memphis East','Hotel','1335 McRee St','Memphis','TN','','https://expedia.com/affiliates/memphis-hotels-quality-inn-suites-memphis-east.illZmVf','Located just minutes from downtown, Quality Inn & Suites Memphis East offers a budget-friendly stay with modern amenities and easy access to the city’s top attractions. This Black-owned hotel in Memphis Tennessee is perfect for business travelers, families, and tourists exploring Memphis, with Graceland, Beale Street, and the Memphis Zoo all within a short drive.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/02/exterior-43.jpg?fit=1024%2C683&ssl=1'),
('Dalmahoy Hotel & Country Club','Hotel','Kirknewton','Edinburgh','EH27 8EB','','https://expedia.com/affiliates/edinburgh-hotels-dalmahoy-hotel-country-club.UjOWde4','Set on a sweeping historic estate just outside Edinburgh, Dalmahoy Hotel & Country Club blends classic Scottish elegance with resort-style comfort. Surrounded by rolling parkland and championship golf courses, the hotel is professionally managed by Pyramid Global Hospitality, led by CEO Warren Fields—placing Dalmahoy among a distinguished portfolio of Black-managed properties under Black executive leadership. With its proximity to Scotland’s capital city and expansive countryside setting, Dalmahoy offers the rare combination of urban access and pastoral retreat.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2026/02/Dalmahoy-Hotel-Country-Club-%E2%80%94-Kirknewton-Edinburgh-Scotland.jpg?fit=1023%2C768&ssl=1'),
('Riverhouse Lodge','Lodge','3075 North Highway 97','Bend','Oregon','','https://expedia.com/affiliates/bend-hotels-riverhouse-on-the-deschutes.CQ87bmh','Set along the scenic Deschutes River, Riverhouse Lodge offers a relaxed, nature-forward stay with sweeping river views and access to outdoor recreation, blending Pacific Northwest charm with full-service comfort. Professional management ensures Black leadership.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2026/02/Riverhouse-Lodge-%E2%80%94-Bend-Oregon-property1.jpg?fit=1024%2C532&ssl=1'),
('Hilton Philadelphia at Penn’s Landing','Hotel','201 S Christopher Columbus Blvd','Philadelphia','PA','(855) 605-0316','https://www.hilton.com/en/hotels/phlpnhh-hilton-philadelphia-at-penns-landing/','Nestled along the scenic Delaware River, Hilton Philadelphia at Penn’s Landing offers guests a unique blend of modern comfort and historic charm. As the city’s only waterfront hotel, it provides panoramic views, upscale amenities, and easy access to Philadelphia’s rich cultural landmarks.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2024/12/waterfront-dining.jpg?fit=1200%2C1800&ssl=1'),
('Barrachina Restaurant','Restaurant','104 C. de la Fortaleza','San Juan','','(787)-725-7912','https://www.yelp.com/biz/barrachina-san-juan-3','Home of the Piña Colada—Authentic Puerto Rican flavor in historic Old San Juan. Native Puerto Rican–owned restaurant in Old San Juan, offering classic Puerto Rican dishes with a warm island-style service in a picturesque, centuries-old building.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/06/Barrachina-Restaurant-San-Juan-Puerto-Rico-4.jpg?fit=562%2C1000&ssl=1'),
('Staverton Park Hotel & Golf Club','Hotel','Daventry Road, Staverton','Daventry','Northamptonshire','','https://expedia.com/affiliates/daventry-hotels-staverton-park-hotel-golf-club.MjNZPor','Countryside Golf Retreat with Black Executive Hospitality Leadership. A relaxed, full-service retreat combining classic comfort with resort-style amenities, set amid rolling English countryside. Ideal for leisure escapes, golf getaways, and business retreats.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2026/02/Staverton-Park-Hotel-Golf-Club-Guestroom-%E2%80%94-Daventry-Northamptonshire-United-Kingdom.jpg?fit=1000%2C667&ssl=1'),
('Renaissance Boulder Flatiron Hotel','Hotel','500 Flatiron Blvd','Broomfield','CO','','https://expedia.com/affiliates/boulder-hotels-renaissance-boulder-flatiron-hotel.sR9jEmu','Nestled in the foothills of the Colorado Rockies, the Renaissance Boulder Flatiron Hotel offers a luxurious blend of sophistication and comfort. This black-owned hotel is committed to delivering exceptional hospitality while fostering inclusivity and community support.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/01/lobby-26.jpg?fit=1200%2C800&ssl=1'),
('Residence Inn by Marriott Boulder Broomfield','Hotel','845 Coal Creek Cir','Louisville','CO','(303) 665-2661','https://expedia.com/affiliates/boulder-hotels-residence-inn-by-marriott-boulder-broomfield.XXcK7PH','Extended Stays with Rocky Mountain Charm. This all-suite black owned hotel in Boulder Colorado ensures a comfortable stay with thoughtful amenities and modern accommodations.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/01/exterior-21.jpg?fit=1200%2C800&ssl=1'),
('Colorado Springs Marriott','Hotel','5580 Tech Center Dr','Colorado Springs','CO','N/A','https://expedia.com/affiliates/colorado-springs-hotels-colorado-springs-marriott.XNNbtyh','Nestled at the base of the majestic Rocky Mountains, Colorado Springs Marriott offers a luxurious retreat for travelers seeking a balance of comfort, sophistication, and breathtaking natural scenery. This black-owned hotel in Colorado Springs delivers exceptional service and a warm, welcoming atmosphere.','https://blackhotelguide.com/wp-content/uploads/2020/01/3-color-268-png-vr-1.png'),
('Black Orchid Resort','Boutique Resort','#2 Dawson Lane','Burrell Boom Village','Belize District','','https://expedia.com/affiliates/burrell-boom-hotels-black-orchid-resort.Aha3IRm','A riverside jungle retreat where tranquil nature meets warm Belizean hospitality. Black Orchid Resort is a Black-owned, family-operated boutique resort blending lush jungle scenery with warm, personalized service. It is recognized as one of Belize’s respected inland retreats, offering a peaceful setting with riverfront views and abundant wildlife.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2026/03/Black-Orchid-Resort-%E2%80%94-Burrell-Boom-Belize-dron-view.jpg?fit=1024%2C768&ssl=1'),
('Fort Lauderdale Marriott North','Hotel','6650 N Andrews Ave','Fort Lauderdale','FL','','https://expedia.com/affiliates/fort-lauderdale-hotels-fort-lauderdale-marriott-north.XKKeVIk','The Fort Lauderdale Marriott North offers a refreshing blend of style, convenience, and thoughtful service—managed by Pyramid Global Hospitality, a major hotel management firm led by trailblazing Black CEO Warren Fields. Located near Florida’s scenic Intracoastal Waterway, this contemporary hotel serves as a welcoming hub for business and leisure travelers alike, delivering elevated experiences for guests from all walks of life.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/05/Fort-Lauderdale-Marriott-North-11.jpg?fit=1024%2C683&ssl=1'),
('Residence Inn by Marriott Boulder Longmont','Hotel','1450 Dry Creek Dr','Longmont','CO','','https://expedia.com/affiliates/boulder-hotels-residence-inn-by-marriott-boulder-longmont.cYzx1iC','Comfortable Extended Stays with a Scenic Backdrop. This black-owned hotel provides the perfect combination of home-like comfort and modern convenience for extended stays or weekend getaways.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/01/market-11.jpg?fit=1200%2C800&ssl=1'),
('Paradise Cove Resort','Resort','Paradise Dr','The Cove','Anguilla','','https://expedia.com/affiliates/cove-bay-hotels-paradise-cove-resort.LCwZ727','Nestled on the breathtaking shores of Anguilla, Paradise Cove Resort is a Black-owned tropical retreat that offers the perfect blend of relaxation, luxury, and island charm. This intimate, all-suite resort is just minutes from the world-famous Rendezvous Bay, providing guests with spacious accommodations, lush gardens, and warm Caribbean hospitality. Whether you''re seeking a romantic getaway, a family vacation, or a peaceful retreat, Paradise Cove delivers an unforgettable island experience.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/02/beach-house.jpg?fit=1000%2C617&ssl=1'),
('Saddlebrook Resort','Resort','5700 Saddlebrook Way','Wesley Chapel','Florida','','https://expedia.com/affiliates/tampa-hotels-saddlebrook-golf-resort-and-spa.z8oOlVm','Premier Sports & Wellness Destination with Black Leadership. Known as a training ground for champions and a retreat for active travelers, the resort blends upscale accommodations with championship golf, elite tennis facilities, wellness experiences, and a full complement of resort amenities.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2026/02/Saddlebrook-Resort-in-Wesley-Chapel-property.jpg?fit=1024%2C576&ssl=1'),
('Jamaican Mi Hungry','Restaurant','225 Centre St','Jamaica Plain','MA','(617)-708-0465','https://www.jamaicamihungry.com/','Jamaican Mi Hungry is a celebrated Black-owned restaurant in Boston, Massachusetts, offering authentic Jamaican cuisine. Founded by Chef Ernie Campbell in 2012, the establishment has evolved from a private chef service into a full-service catering company, food truck, and brick-and-mortar restaurant.','https://blackhotelguide.com/wp-content/uploads/2020/01/3-color-268-png-vr-1.png'),
('Marley Resort & Spa','Resort','West Bay Street','Nassau','New Providence Island','','https://expedia.com/affiliates/nassau-hotels-marley-resort-spa.BQQeVwP','Experience a truly iconic Caribbean escape at Marley Resort & Spa, an oceanfront boutique retreat located on the world-famous Cable Beach in Nassau, Bahamas. Once the private vacation home of reggae legend Bob Marley and Rita Marley, this historic estate has been transformed into an intimate luxury resort that blends Afro-Caribbean design, holistic wellness, and the unmistakable rhythm of reggae culture.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2026/03/Marley-Resort-Spa-Nassau-Bahamas-.jpg?fit=1200%2C900&ssl=1'),
('iKhaya Lodge & Conference Centre','Hotel','Dunkley Square','Cape Town','Western Cape','','https://expedia.com/affiliates/cape-town-hotels-ikhaya-lodge-conference-centre.YGQLpe6','Located in the heart of Cape Town, iKhaya Lodge is a Black-owned hotel in South Africa that offers a warm, welcoming atmosphere infused with African design, culture, and hospitality. Perched on the slopes of Table Mountain, this intimate lodge provides breathtaking views of the city and an immersive experience that highlights local craftsmanship and heritage.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/02/iKhaya-Lodge.jpg?fit=1200%2C797&ssl=1')
)
INSERT INTO public.businesses (name, business_name, category, address, city, state, phone, website, description, banner_url, owner_id, listing_status, is_verified)
SELECT s.business_name, s.business_name, s.category, NULLIF(s.address,''), NULLIF(s.city,''), NULLIF(s.state,''), NULLIF(s.phone,''), NULLIF(s.website,''), NULLIF(s.description,''), NULLIF(s.banner_url,''), 'bd72a75e-1310-4f40-9c74-380443b09d9b'::uuid, 'live', true
FROM src s
WHERE NOT EXISTS (SELECT 1 FROM public.businesses b WHERE lower(regexp_replace(b.business_name,'[^A-Za-z0-9]+','','g')) = lower(regexp_replace(s.business_name,'[^A-Za-z0-9]+','','g')));