INSERT INTO businesses (business_name, name, description, category, address, city, state, zip_code, phone, email, website, is_verified, latitude, longitude, owner_id, banner_url)
VALUES 
(
  'Mama Sheila''s House of Soul',
  'Mama Sheila''s House of Soul',
  'A pillar of the South Minneapolis community since 2016, Mama Sheila''s serves up the freshest ingredients with delicious secret recipes. Founded by Mama Sheila and Frederick Brathwaite, what began as church catering has evolved into a beloved neighborhood hotspot for authentic soul food.',
  'Restaurant',
  '3744 Bloomington Ave',
  'Minneapolis',
  'MN',
  '55407',
  '(612) 886-3265',
  'info@mamasheilas.com',
  'https://mamasheilas.com',
  true,
  44.9390,
  -93.2320,
  'bd72a75e-1310-4f40-9c74-380443b09d9b',
  '/images/businesses/mama-sheilas-minneapolis.jpg'
),
(
  'Lillie Pearl',
  'Lillie Pearl',
  'A New American restaurant in Richmond offering impeccable service, gracious hospitality, and delicious southern-inspired cuisine. Recently relocated to 305 Brook Rd with stunning city views, Lillie Pearl delivers memorable dining experiences with both upstairs and downstairs options.',
  'Restaurant',
  '305 Brook Rd',
  'Richmond',
  'VA',
  '23220',
  '(804) 432-7795',
  'info@lilliepearlrva.com',
  'https://www.lilliepearlrva.com',
  true,
  37.5538,
  -77.4365,
  'bd72a75e-1310-4f40-9c74-380443b09d9b',
  '/images/businesses/lillie-pearl-richmond.jpg'
),
(
  'Saucy''s Southern BBQ & Cuisine',
  'Saucy''s Southern BBQ & Cuisine',
  'A Black-owned BBQ destination in the heart of Denver University serving combo plates of grilled ribs, pulled pork, chicken, and classic Southern sides. Known for friendly service, consistent quality, and generous portions that keep the community coming back.',
  'Restaurant',
  '2100 S University Blvd',
  'Denver',
  'CO',
  '80210',
  '(720) 484-6035',
  'info@saucyssouthernbbq.com',
  'https://saucyssouthernbbq.com',
  true,
  39.6780,
  -104.9610,
  'bd72a75e-1310-4f40-9c74-380443b09d9b',
  '/images/businesses/saucys-southern-bbq-denver.jpg'
);