WITH src(business_name,category,address,city,state,phone,website,description,banner_url) AS (VALUES
('Mills House Charleston, Curio Collection by Hilton','Hotel','115 Meeting Street','Charleston','SC','','https://expedia.com/affiliates/charleston-hotels-mills-house-charleston.UBtZm4J','A true icon in Charleston’s historic district, this black-owned hotel blends classic Southern charm with modern sophistication. With its signature pink façade, elegant interiors, and rooftop pool, this luxurious retreat offers an unforgettable stay just steps from the city’s best dining, shopping, and historic landmarks.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/02/mills-house-charleston.jpg?fit=1200%2C870&ssl=1'),
('Ocean Terrace Inn','Hotel','Wigley Avenue, Fortlands','Basseterre','St. Kitts','','https://expedia.com/affiliates/basseterre-hotels-ocean-terrace-inn.AjQtZ6b','A Scenic Caribbean Retreat in St. Kitts offering breathtaking ocean views, personalized service, and authentic Caribbean charm. Ideal retreat for relaxation, adventure, and cultural exploration.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/02/ocean-terrace-inn-2.jpg?fit=1200%2C800&ssl=1'),
('Clearwater Beach Marriott Suites on Sand Key','Resort','1201 Gulf Blvd','Clearwater Beach','FL','','https://expedia.com/affiliates/st-petersburg-clearwater-hotels-clearwater-beach-marriott-suites-on-sand-key.HeH7Wtt','Perched on the scenic shores of Sand Key, this beach front resort on Clearwater Beach is a serene waterfront oasis perfect for family getaways, romantic retreats, and relaxing vacations. With stunning views of Clearwater Bay and a short walk to the famous white sands of Clearwater Beach, this black-owned beachfront resort in Clearwater Beach Florida offers a blend of coastal charm and modern comfort.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/01/exterior-aerial-bay-view.jpg?fit=1000%2C667&ssl=1'),
('InterContinental Seattle Bellevue','Hotel','850 103rd Avenue NE','Bellevue','Washington','','https://expedia.com/affiliates/seattle-hotels-intercontinental-bellevue-at-the-avenue.yEwKgQ5','Luxury Downtown Bellevue Retreat with Black Leadership. Situated in the thriving heart of downtown Bellevue, InterContinental Seattle Bellevue presents a refined luxury experience in one of the Pacific Northwest’s most dynamic urban centers. The hotel blends contemporary design with upscale comfort, providing a sophisticated destination for business travelers, vacationers, and anyone seeking a premier gateway to Seattle and its surrounding attractions. This property is professionally managed by Pyramid Global Hospitality, led by CEO Warren Fields, making InterContinental Seattle Bellevue a Black-managed hotel under Black executive leadership.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2026/02/InterContinental-Seattle-Bellevue-by-IHG-%E2%80%94-Bellevue-Washington-USA.jpg?fit=1024%2C683&ssl=1'),
('Marriott Marquis Washington, D.C.','Hotel','901 Massachusetts Avenue NW','Washington, D.C.','DC','','https://expedia.com/affiliates/washington-hotels-marriott-marquis-washington.kBZZi27','Nestled in the heart of downtown Washington, D.C., the black-owned Marriott Marquis Washington, D.C. is a sleek urban oasis that blends modern luxury with grand-scale hospitality. Known as the largest hotel in Washington, D.C., it features striking contemporary architecture and a dramatic 55-foot sculpture set beneath its sun-filled atrium.','https://blackhotelguide.com/wp-content/uploads/2020/01/3-color-268-png-vr-1.png'),
('SAHARA Hotel, Las Vegas','Hotel','2535 S Las Vegas Blvd','Las Vegas','NV','','https://expedia.com/affiliates/las-vegas-hotels-sahara-las-vegas.WDBzp1i','SAHARA Las Vegas is a minority-owned hotel that revitalized a landmark blending vintage Vegas allure with modern sophistication. This upscale, non-gaming, smoke-free property offers stylish accommodations, diverse dining options, wellness amenities, and event spaces.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/05/sahara-las-vegas.jpg?fit=740%2C650&ssl=1'),
('Inkwell Beach House','Bed & Breakfast','83 Sea View Ave','Oak Bluffs','MA','','','Historic Charm and Oceanfront Serenity in Oak Bluffs. A Black-owned bed and breakfast that blends Victorian elegance with modern comfort, offering an authentic Martha’s Vineyard experience. Includes stunning ocean views and easy beach access.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/05/Inkwell-Beach-House-Marthas-Vineyard-2.jpg?fit=1024%2C768&ssl=1'),
('La Quinta Resort & Club, Curio Collection by Hilton','Resort','49-499 Eisenhower Dr','La Quinta','CA','','','Nestled at the base of the Santa Rosa Mountains in California’s Coachella Valley, La Quinta Resort & Club is a legendary hideaway renowned for its Spanish Revival architecture, lush grounds, and decades-long legacy of hosting Hollywood icons. This five-star desert resort combines timeless elegance with modern luxury, offering more than 600 casitas, suites, and villas; 41 sparkling pools; championship golf; award-winning dining; and a world-class spa.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/05/Black-led-luxury-resort-La-Quinta-Resort-Club-3.jpg?fit=1024%2C683&ssl=1'),
('The Inn at Folkston Bed & Breakfast','Bed & Breakfast','3576 Main Street','Folkston','GA','','https://booking.stay22.com/blackhotelguide/40Y2SxNtAH','Located in the heart of Folkston, Georgia, The Inn at Folkston is a deluxe, Black-owned bed and breakfast that blends relaxed southern hospitality with unique attention to detail. Offering cozy suites, rich local character, and a peaceful retreat, it''s perfect for travelers keen on nature, history, or slowdowns.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/09/The-Inn-at-Folkston-Bed-Breakfast.jpg?fit=1000%2C750&ssl=1'),
('The Laylow, Autograph Collection','Hotel','2299 Kūhiō Ave.','Honolulu','HI','','https://expedia.com/affiliates/honolulu-hotels-the-laylow.HkjF1b5','Perched above the energy of Honolulu’s Kuhio Avenue, The Laylow, Autograph Collection offers a serene hideaway blending vintage Hawaiian charm with sleek, mid-century modern design. Managed by Pyramid Global Hospitality, it champions inclusive leadership and curated experiences that highlight the spirit of place. With lush greenery, retro-cool aesthetics, and a focus on local flavor, The Laylow captures the essence of laid-back luxury on Oʻahu.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/05/The-Laylow-Autograph-Collection-Waikiki-HI-9.jpg?fit=1024%2C683&ssl=1'),
('Little Havana: Cigar & Rum Tasting Experience','Experience','Bay of Pigs Monument, 806 SW 13th Ave','Miami','FL','','','An unforgettable guided tour that immerses you in the rich traditions of Cuba right in the heart of Florida. Enjoy tastings of premium Cuban-style rums and hand-rolled cigars while learning about the history and culture of Little Havana.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/07/Little-Havana-Cigar-Rum-Tasting-Experience.jpg?fit=719%2C480&ssl=1'),
('Chicago Mahogany Tours','Tour Company','1801 South Indiana Avenue','Chicago','IL','','https://www.chicagomahogany.com/','This Black-owned Chicago tour company offers an immersive journey through the city of Chicago''s Black history, culture, and architectural gems. Tours are led by noted historian and author Sherman “Dilla” Thomas, who engages guests with storytelling and insights into significant locations within Chicago’s African American heritage.','https://blackhotelguide.com/wp-content/uploads/2020/01/3-color-268-png-vr-1.png'),
('The Bankers Alley Hotel, Nashville - Black Hotel Guide','Hotel','510 Broadway','Nashville','TN','','','Discover the perfect blend of modern sophistication and Southern charm at The Bankers Alley Hotel, Tapestry Collection by Hilton—a luxury Black-owned hotel in the heart of Nashville. This boutique property is a masterful historic restoration that doubles as both an upscale hotel and a contemporary art experience.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/02/hotel-exterior-21c-museum.jpg?resize=653%2C199&ssl=1'),
('Salamander Washington DC','Hotel','','Washington DC','','','','Situated along the scenic Southwest Waterfront, Salamander Washington DC offers an unparalleled blend of luxury, sophistication, and comfort. This Five-star Black-owned hotel in Washington DC, part of Sheila Johnson’s prestigious Salamander Collection, is a haven of refined hospitality, world-class amenities, and breathtaking city views.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/02/drone-view-10.jpg?resize=653%2C199&ssl=1'),
('Hampton Inn, Douglas, Georgia','Hotel','233 223 Martin Luther King Jr Blvd','Savannah','GA','','','Welcome to the Hampton Inn in Douglas, Georgia — proudly Black-owned and operated by Elsie Capital, a firm founded by trailblazing entrepreneur Kendra Plummer, one of the few Black women leading in the hospitality investment space. This highly rated hotel blends contemporary comfort with small-town charm, making it a top choice for travelers seeking both …','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/06/Hampton-Inn-Douglas-Georgia.jpg?resize=653%2C199&ssl=1'),
('Wanderstay Boutique Hotel','Boutique Hotel','520 Sampson St','Houston','TX','','','A Stylish & Culturally Vibrant Stay in the Heart of Houston. The Wanderstay Boutique Hotel is a Black-owned gem designed for travelers seeking a unique, stylish, and comfortable stay, blending bold aesthetics with modern amenities.','https://blackhotelguide.com/wp-content/uploads/2020/01/3-color-268-png-vr-1.png'),
('DoubleTree by Hilton Houston Medical Center Hotel & Suites','Hotel','6800 Main Street','Houston','TX','','','Situated in the heart of the Texas Medical Center, the black-owned Houston Texas hotel offers a welcoming stay with spacious accommodations, modern amenities, and signature warm hospitality. Whether you’re visiting for medical purposes, business, or leisure, this hotel provides easy access to top Houston destinations.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/01/main-street-bar-and-grill1.jpg?fit=1200%2C800&ssl=1'),
('Hilton Garden Inn Houston Energy Corridor','Hotel','12245 Katy Freeway','Houston','TX','','https://expedia.com/affiliates/houston-hotels-hilton-garden-inn-houston-energy-corridor.OFAOgxD','The Hilton Garden Inn Houston Energy Corridor offers exceptional comfort and convenience for travelers visiting one of Houston’s most prominent business districts. Situated along I-10, this black-owned hotel in Houston Texas is ideal for both business and leisure guests, with easy access to major corporations, shopping, dining, and entertainment. Whether you’re attending a meeting or exploring the city, the hotel’s well-appointed amenities and welcoming service ensure a relaxing stay.','https://blackhotelguide.com/wp-content/uploads/2020/01/3-color-268-png-vr-1.png'),
('Houston Marriott Westchase','Hotel','2900 Briarpark Drive','Houston','TX','','','Situated in the heart of Houston’s vibrant Westchase District, the Houston Texas Black-owned hotel Houston Marriott Westchase offers an upscale stay for business and leisure travelers alike. With stylish accommodations, excellent dining options, and premium amenities, guests can enjoy a seamless blend of comfort and convenience.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/01/event-space-5.jpg?fit=480%2C320&ssl=1'),
('Courtyard New York Manhattan / Upper East Side','Hotel','410 E 92nd St','New York','NY','','https://expedia.com/affiliates/new-york-hotels-courtyard-by-marriott-new-york-manhattanupper-east-side.jxRZ8yS','Conveniently located in one of Manhattan’s most prestigious neighborhoods, this stylish black-owned hotel in Manhattan’s Upper East Side provides everything you need for a memorable visit.','https://blackhotelguide.com/wp-content/uploads/2020/01/3-color-268-png-vr-1.png')
)
INSERT INTO public.businesses (name, business_name, category, address, city, state, phone, website, description, banner_url, owner_id, listing_status, is_verified)
SELECT s.business_name, s.business_name, s.category, NULLIF(s.address,''), NULLIF(s.city,''), NULLIF(s.state,''), NULLIF(s.phone,''), NULLIF(s.website,''), NULLIF(s.description,''), NULLIF(s.banner_url,''), 'bd72a75e-1310-4f40-9c74-380443b09d9b'::uuid, 'live', true
FROM src s
WHERE NOT EXISTS (SELECT 1 FROM public.businesses b WHERE lower(regexp_replace(b.business_name,'[^A-Za-z0-9]+','','g')) = lower(regexp_replace(s.business_name,'[^A-Za-z0-9]+','','g')));