INSERT INTO businesses (business_name, name, description, category, address, city, state, zip_code, phone, email, website, is_verified, latitude, longitude, owner_id, banner_url)
VALUES 
(
  'Minnie Bell''s Soul Movement',
  'Minnie Bell''s Soul Movement',
  'Delicious home-style food combining soulful flavors and warmth of the south. Located in San Francisco''s historic Fillmore District, Minnie Bell''s serves rosemary fried chicken, smothered pork chops, collard greens, and other soul food classics.',
  'Restaurant',
  '1375 Fillmore St',
  'San Francisco',
  'CA',
  '94115',
  '(415) 346-3990',
  'info@minniebellssoul.com',
  'https://www.minniebellssoul.com',
  true,
  37.7823,
  -122.4318,
  'bd72a75e-1310-4f40-9c74-380443b09d9b',
  '/images/businesses/minnie-bells-soul-movement.jpg'
),
(
  'The Four Way',
  'The Four Way',
  'A Memphis soul food institution since 1946, The Four Way has served legends from Martin Luther King Jr. to Aretha Franklin. Known for its catfish, fried chicken, mac and cheese, and greens, this Soulsville landmark continues a legacy of community and incredible Southern cooking.',
  'Restaurant',
  '998 Mississippi Blvd',
  'Memphis',
  'TN',
  '38126',
  '(901) 507-1519',
  'info@fourway901.com',
  'https://www.fourway901.com',
  true,
  35.1190,
  -90.0370,
  'bd72a75e-1310-4f40-9c74-380443b09d9b',
  '/images/businesses/four-way-memphis.jpg'
),
(
  'Kann',
  'Kann',
  'A celebrated Haitian restaurant by James Beard Award-winning chef Gregory Gourdet. Kann showcases the vibrant flavors of Haiti through wood-fired cooking, fresh seafood, and bold Caribbean spices in a stunning Portland dining room.',
  'Restaurant',
  '548 SE Ash St',
  'Portland',
  'OR',
  '97214',
  '(503) 206-7485',
  'careers@kannrestaurant.com',
  'https://kannrestaurant.com',
  true,
  45.5214,
  -122.6599,
  'bd72a75e-1310-4f40-9c74-380443b09d9b',
  '/images/businesses/kann-portland.jpg'
);