
INSERT INTO businesses (
  id,
  name,
  business_name,
  description,
  category,
  address,
  city,
  state,
  zip_code,
  phone,
  email,
  website,
  logo_url,
  banner_url,
  is_verified,
  listing_status,
  owner_id,
  created_at,
  updated_at,
  latitude,
  longitude,
  average_rating,
  review_count
) VALUES (
  'af3e2b91-7c14-4d88-a621-5f9e8d3c1b47',
  'Amhad Freeman Interiors',
  'Amhad Freeman Interiors',
  'A Black-owned luxury interior design firm with offices in Chicago and Nashville, delivering refined residential design through thoughtful details and effortless sophistication. Specializing in modern interiors for the discerning client.',
  'Interior Design',
  'Chicago, IL',
  'Chicago',
  'IL',
  '60601',
  '(773) 245-6320',
  'amhad@amhadfreeman.com',
  'https://www.amhadfreeman.com',
  '/images/businesses/amhad-freeman-logo.png',
  '/images/businesses/amhad-freeman-banner.jpg',
  true,
  'live',
  'bd72a75e-1310-4f40-9c74-380443b09d9b',
  now(),
  now(),
  41.8827,
  -87.6233,
  5.0,
  0
);
