WITH src(business_name,category,address,city,state,phone,website,description,banner_url) AS (VALUES
('Martin Luther King Jr. National Historical Park','Museum','450 Auburn Avenue NE','Atlanta','GA','','','The Martin Luther King Jr. National Historical Park is an African American Museum that spans approximately 35 acres and offers an immersive journey through the life and legacy of Dr. Martin Luther King Jr.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2024/12/Martins-Home.jpg?fit=1000%2C750&ssl=1'),
('Blue Apple Beach, Hotel','Hotel','Playa Mamon #1-1 Bocachica','Cartagena','','','https://expedia.com/affiliates/cartagena-hotels-blue-apple-beach-house.aWbYNSA','A Black-Owned Caribbean Escape in Colombia, Blue Apple Beach blends laid-back vibes with eco-luxury and sustainability. Known for its boho-chic accommodations, farm-to-table cuisine, and vibrant social scene, it''s perfect for a stylish and relaxed getaway.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/02/blue-apple-beach-hotel-22.jpg?fit=1100%2C1467&ssl=1'),
('Begoña Cliff Hotel','Boutique Hotel','West End Road','Negril','Jamaica','','','Black-Owned Boutique Cliffside Retreat with Personalized Hospitality. Perched dramatically above the turquoise waters of Jamaica’s famed West End, Begoña Cliff Hotel is a Black-owned boutique hotel known for its warm Jamaican hospitality and stunning ocean views. It offers stylish guest rooms and suites, on-site dining, and personalized services for a unique Caribbean escape.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2026/02/Begona-Cliff-Hotel-%E2%80%94-Negril-Jamaica-bar.jpg?fit=1024%2C498&ssl=1'),
('Costa d’Este Beach Resort & Spa, Florida','Resort','3244 Ocean Dr','Vero Beach','FL','','https://expedia.com/affiliates/vero-beach-hotels-costa-deste-beach-resort-and-spa.sTfG9X9','Oceanfront luxury meets soulful hospitality in Vero Beach. Owned by music legend Gloria Estefan and her husband Emilio, Costa d’Este Beach Resort & Spa offers a sophisticated yet soulful getaway in Florida’s Treasure Coast.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/05/oceanfront-king-room-v3498015.jpg?fit=1000%2C667&ssl=1'),
('La Concha Renaissance San Juan Resort','Resort','1077 Ashford Ave','San Juan','Puerto Rico','','https://expedia.com/affiliates/san-juan-hotels-la-concha-renaissance-san-juan-resort.eb9FO2J','Modern Luxury Meets Tropical Sophistication in Condado, featuring stylish accommodations, culinary delights, and a beachfront location.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/06/La-Concha-Renaissance-San-Juan-Resort.jpg?fit=1024%2C683&ssl=1'),
('Hampton Inn Ft. Walton Beach','Hotel','1112 Santa Rosa Blvd','Fort Walton Beach','FL','','https://expedia.com/affiliates/pensacola-hotels-hampton-inn-ft-walton-beach.RITEu6h','This black-owned hotel on Walton Beach, Florida in the Gulf of Mexico, is located directly on the pristine white sands of Florida’s Emerald Coast. Hampton Inn Ft. Walton Beach offers a relaxed and welcoming retreat for families, couples, and business travelers. With stunning Gulf views, easy beach access, and modern amenities, this hotel ensures a memorable stay filled with comfort and convenience.','https://blackhotelguide.com/wp-content/uploads/2025/01/hampton-inn-ft-walton.jpg?fit=1000%2C1333&ssl=1'),
('Mariners Hotel','Hotel','Villa Beach, Villa','St. Vincent','St. Vincent and the Grenadines','','https://expedia.com/affiliates/villa-hotels-mariners-hotel.peqEC85','A locally owned beachfront hotel with authentic Vincentian hospitality, offering comfortable guest rooms, direct beach access, and a vibrant on-site restaurant.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2026/03/Mariners-Hotel-St.-Vincent-the-Grenadines-double-room.jpg?fit=1200%2C670&ssl=1'),
('Casa Congo – Rayo Verde – Restaurante','Boutique Hotel / Resort','Calle Genea, detrás de la Casa de la Aduana','Portobelo','Panama','','https://expedia.com/affiliates/portobelo-hotels-casa-congo-rayo-verde-restaurante.JsnibL0','A cultural boutique stay where Afro-Congo heritage, art, and community preservation come together. Casa Congo functions as both a guesthouse and a living cultural institution — where hospitality directly supports community empowerment.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2026/03/Casa-Congo-in-Portobelo-Panama.jpg?fit=1024%2C575&ssl=1'),
('Negril Treehouse Resort','Resort','','Negril','','1 (876) 957-4287','http://negriltreehouse.net/','This black-owned resort in Negril Jamaica is nestled along the famous Seven Mile Beach and embodies the spirit of authentic Jamaican hospitality. Surrounded by lush tropical gardens and the Caribbean Sea, it offers comfortable accommodations, delectable dining, and easy access to local attractions.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/01/outdoorspa.jpg?fit=1024%2C683&ssl=1'),
('Ocean West Boutique Hotel','Hotel','3H94+8G2, W Bay St','Nassau','','','https://expedia.com/affiliates/nassau-hotels-ocean-west-boutique-hotel.fUPIZC7','Perched on a scenic hilltop with breathtaking views of the turquoise waters of the Atlantic, Ocean West Boutique Hotel offers an intimate and serene retreat in Nassau, Bahamas. This charming, upscale black-owned hotel blends Caribbean elegance with personalized hospitality, providing a peaceful escape just minutes from Cable Beach and Nassau’s vibrant attractions.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/02/ocean-west-boutique-hotel-1.jpg?fit=640%2C480&ssl=1'),
('Renaissance Pittsburgh Hotel','Hotel','107 6th St','Pittsburgh','PA','','https://expedia.com/affiliates/pittsburgh-hotels-renaissance-pittsburgh-hotel.DeuIpBW','Historic Elegance Meets Modern Luxury in Downtown Pittsburgh. Nestled in Pittsburgh’s vibrant Cultural District, this Black-owned hotel offers a sophisticated stay defined by timeless architecture and contemporary comfort, featuring elegant guest rooms and on-site dining.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/01/renaissance-pittsburgh.jpg?fit=1000%2C667&ssl=1'),
('Rondel Village','Resort','7MW6+MPW, Norman Manley Blvd','Negril','','','https://expedia.com/affiliates/negril-hotels-rondel-village.lIZJpr8','Nestled along the famous Seven Mile Beach, Rondel Village is a Black-owned resort in Jamaica that offers an intimate island experience with tropical charm and warm hospitality.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/03/Rondel-Village.jpg?fit=1024%2C681&ssl=1'),
('Serenity by Tilair','Villa','500 29th Ave S','Atlantic Beach','SC','','https://expedia.com/affiliates/north-myrtle-beach-hotels-serenity-by-tilair-7-bd65-ba-new-house.ZEgtaNg','A stunning upscale Black-women-owned villa in Atlantic Beach, SC that offers a serene and stylish retreat, accommodating 16+ guests, featuring seven beautiful bedrooms and beds 6.5 baths. Designed for travelers seeking comfort, culture, and coastal charm, this private getaway blends modern elegance with the rich history of the area.','https://blackhotelguide.com/wp-content/uploads/2020/01/3-color-268-png-vr-1.png'),
('Punta Borinquen Resort','Resort','90 Wing Rd','Aguadilla','Puerto Rico','','https://expedia.com/affiliates/aguadilla-hotels-punta-borinquen-resort.Vj7weWl','Puerto Rican-owned beachfront resort featuring modern amenities, a poolside restaurant, and a convention center, close to famous surf beaches.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/06/Punta-Borinquen-Resort-Aguadilla-Puerto-Rico-restaurant-1.jpg?fit=1024%2C768&ssl=1'),
('Stonefield Villa Resort','Resort','Stonefield Estate Resort','Soufrieire','','','https://expedia.com/affiliates/soufriere-hotels-stonefield-villa-resort-adults-only.v4IdFgP','A secluded Caribbean retreat offering private luxury villas with plunge pools, breathtaking views of the Pitons, and an intimate connection with nature.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/02/stonefield-villa-resort-19.jpg?fit=1200%2C800&ssl=1'),
('S Hotel Montego Bay','Resort','7 Jimmy Cliff Boulevard','Montego Bay','Jamaica','.','https://expedia.com/affiliates/montego-bay-hotels-s-hotel-jamaica.lAMpii6','Locally-owned, Award-Winning All-Inclusive Resort Overlooking Doctor’s Cave Beach. Featuring luxury all-inclusive dining, rooftop pools, spa treatments, and culturally immersive experiences.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2026/02/S-Hotel-Montego-Bay-%E2%80%94-Montego-Bay-Jamaica-rum-flights.jpg?fit=1024%2C724&ssl=1'),
('Tamboo Beside the Pointe','Inn','Carretera 413 Ramal','Rincón','00677','','https://expedia.com/affiliates/rincon-hotels-tamboo-beside-the-pointe.6pGomYW','Tamboo Beside the Pointe is a celebrated beachfront inn, restaurant and bar, Puerto Rican-owned and family-operated since 2000. Located on Sandy Beach, it offers oceanfront lodging, live local music, and a laid-back surfside vibe.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/06/Tamboo-Beside-the-Pointe-Puerto-Rico.jpg?fit=1973%2C1146&ssl=1'),
('Sentinel','Hotel','614 SW 11th Avenue','Portland','OR','','https://expedia.com/affiliates/portland-hotels-sentinel.0P2R7in','Luxury boutique hotel blending historic grandeur with modern style. Features unique guestrooms, top dining options, and vibrant nightlife.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2026/03/Sentinel-boutique-hotel-Portland-OR.jpg?fit=1024%2C683&ssl=1'),
('The Westin Portland Harborview','Hotel','157 High St','Portland','ME','','https://expedia.com/affiliates/portland-hotels-the-westin-portland-harborview.kW4lxzd','Historic elegance with modern luxury in the heart of downtown Portland, featuring contemporary rooms, fine dining, and a rooftop lounge.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/05/The-Westin-Portland-Harborview-ME-18.jpg?fit=1024%2C683&ssl=1'),
('Hotel Bennett','Hotel','404 King Street','Charleston','SC','','https://expedia.com/affiliates/charleston-hotels-hotel-bennett.9NXShLZ','Experience Southern luxury at its finest at the black-owned Hotel Bennett in Charleston South Carolina, a premier destination in Charleston, SC. Located on historic Marion Square, this elegant hotel combines timeless charm with modern sophistication, making it a favorite among discerning travelers. Whether you’re visiting for a romantic getaway, a special event, or a relaxing retreat, this African American owned hotel offers an unparalleled experience in the heart of Charleston.','https://i0.wp.com/blackhotelguide.com/wp-content/uploads/2025/01/Hotel-Bennett.jpg?fit=1360%2C661&ssl=1')
)
INSERT INTO public.businesses (name, business_name, category, address, city, state, phone, website, description, banner_url, owner_id, listing_status, is_verified)
SELECT s.business_name, s.business_name, s.category, NULLIF(s.address,''), NULLIF(s.city,''), NULLIF(s.state,''), NULLIF(s.phone,''), NULLIF(s.website,''), NULLIF(s.description,''), NULLIF(s.banner_url,''), 'bd72a75e-1310-4f40-9c74-380443b09d9b'::uuid, 'live', true
FROM src s
WHERE NOT EXISTS (SELECT 1 FROM public.businesses b WHERE lower(regexp_replace(b.business_name,'[^A-Za-z0-9]+','','g')) = lower(regexp_replace(s.business_name,'[^A-Za-z0-9]+','','g')));