INSERT INTO businesses (business_name, name, description, category, address, city, state, zip_code, phone, email, website, is_verified, latitude, longitude, owner_id, banner_url)
VALUES 
(
  'Jackson''s Catfish Corner',
  'Jackson''s Catfish Corner',
  'A Seattle institution since 1985, Jackson''s Catfish Corner is a Black-owned family restaurant in the Central District serving legendary Southern soul food. Famous for their flaky catfish with homemade tartar sauce, fried chicken, and classic sides that have kept the community coming back for nearly four decades.',
  'Restaurant',
  '2218 S Jackson St',
  'Seattle',
  'WA',
  '98144',
  '(206) 420-3911',
  'info@jacksonscatfishcorner.com',
  'https://blackrestaurantweeks.com/brw-campaigns/jacksons-catfish-corner/',
  true,
  47.5994,
  -122.3025,
  'bd72a75e-1310-4f40-9c74-380443b09d9b',
  '/images/businesses/jacksons-catfish-corner-seattle.jpg'
),
(
  'The Juicy Crab Jacksonville',
  'The Juicy Crab Jacksonville',
  'A Black-owned seafood destination in the heart of Jacksonville''s Westside. The Juicy Crab serves up fresh, flavorful seafood with Southern flair. Known for generous portions, a lively atmosphere, and a menu that brings the community together over great food.',
  'Restaurant',
  '8106 Blanding Blvd',
  'Jacksonville',
  'FL',
  '32244',
  '(904) 379-5517',
  'info@thejuicycrabjax.com',
  'http://www.thejuicycrabjax.com',
  true,
  30.2280,
  -81.7640,
  'bd72a75e-1310-4f40-9c74-380443b09d9b',
  '/images/businesses/juicy-crab-jacksonville.jpg'
),
(
  'Wah Gwan',
  'Wah Gwan',
  'A vibrant Jamaican and Nigerian fusion restaurant in Kansas City owned by Tanyech "Tan" Yarbrough. Wah Gwan blends Caribbean and West African flavors with dishes like oxtail, jerk chicken, rasta pasta, and fried plantains. An authentic, inviting atmosphere that transcends borders.',
  'Restaurant',
  '6228 Troost Ave',
  'Kansas City',
  'MO',
  '64110',
  '(816) 895-3427',
  'info@wahgwantan.com',
  'https://wahgwantan.com',
  true,
  39.0320,
  -94.5710,
  'bd72a75e-1310-4f40-9c74-380443b09d9b',
  '/images/businesses/wah-gwan-kc.jpg'
);